### ISSUE TITLE
Doesn't work properly in iOS

### ISSUE THREAD

**Issue by Hackintosh** [eisbehr-/jquery.lazy#101]
Check this video 
https://youtu.be/pBZRj-w2hJk
The following is the Lazy config I'm using
This is the URL of error https://www.hackintosh.computer/1121/install-macos-high-sierra-on-pc/

```

 $('img').Lazy({
        // your configuration goes here
attribute: 'data-computer',
srcsetAttribute: 'data-computerSet',
removeAttribute: true,
autoDestroy: false,
threshold: 100,
        onError: function(element) {
            console.log('error loading ' + element.data('src'));
        }
    });
 
$('iframe').Lazy({
        // your configuration goes here
removeAttribute: true,
threshold: 100,
autoDestroy: false,
        onError: function(element) {
            console.log('error loading ' + element.data('src'));
        }
    });
 
```

**Comment by eisbehr-** [comment]
Hello @Hackintosh 

I don't have an iOS device here for testing. When you say "error", is there any console output you have, or is there just anything missing? And belongs the problem to the images, or to the iframes?

**Comment by eisbehr-** [comment]
Closed because of missing user input.
