### ISSUE TITLE
Element img is missing required attribute src

### ISSUE THREAD

**Issue by alexanderlukjanenko** [eisbehr-/jquery.lazy#102]
When using lazy plugin I got error from https://validator.w3.org
Is there a way to use your plugin and pass validation?

**Comment by eisbehr-** [comment]
Of course you get this error, `src` is a mandatory field for `img` tag. But no browser will have a problem when you miss the `src` attribute. It's just a warning you can ignore.

But solving this _issue_ is pretty easy. Just add an empty `src` attribute to all your images. That is generally a good practice to do so.

```HTML
<img src="" data-src="image.jpg" />
```

That's it. :wink:
