### ISSUE TITLE
Fade in effect with background images

### ISSUE THREAD

**Issue by xpander001** [eisbehr-/jquery.lazy#103]
I'm trying to make work the fadeIn effect with background images. Is it possible or only available for img tags?

**Comment by xpander001** [comment]
Solved. Sorry for bothering!

**Comment by killfrog47** [comment]
How was this solved? Im having trouble getting background images to fade in.

**Comment by xpander001** [comment]
@killfrog47 I created my own version fading images.

**Comment by neoneddy** [comment]
@xpander001 Why do you tease us so?   Please, share this sacred knowledge.

**Comment by eisbehr-** [comment]
@killfrog47 @xpander001 In general you can't fade background images in any way. You can fade the whole element, but then the content fades too. If you want to fade the background only, place an `img` tag in the back of your element with `position: absolute` and fade this element.

**Comment by eisbehr-** [comment]
@killfrog47 @neoneddy In general you can't fade background images in any way. You can fade the whole element, but then the content fades too. If you want to fade the background only, place an img tag in the back of your element with position: absolute and fade this element.
