### ISSUE TITLE
Content Fade in

### ISSUE THREAD

**Issue by jonah-corbin** [eisbehr-/jquery.lazy#104]
I'm not sure if this is already a feature, or if I should just do this myself, but It'd be cool if the content faded in on load.

The website simple.com fades in their content on scroll. Its pretty cool.

**Comment by eisbehr-** [comment]
A very short look to the [page](http://jquery.eisbehr.de/lazy/example_make-use-of-effects) or the [readme](https://github.com/eisbehr-/jquery.lazy#configuration-parameters) would have give you the answer instantly. 😉

**Comment by jonah-corbin** [comment]
Sorry, I didn’t explain myself. The “effect” configuration parameter only works for images, and not loaded html content. Check out the website I linked. On a desktop each section, of both text and images, loads with a fade in. 

I got it to work though so it’s not important. I just wish the parameter was more robust.

**Comment by eisbehr-** [comment]
Well, the `effect` config parameter is supported by everything within the base plugin. But keep in mind that loading html content is not a core functionality. This is delivered within an own plugin itself. It is not possiblie to implement all config parameters for each loader plugin too. I'm sorry for the confusion.

But as you got it working, implementing this on your own is pretty easy. Just use the callbacks and you can access the config parameters on your own too.
