### ISSUE TITLE
Dynamically loaded content

### ISSUE THREAD

**Issue by AzmaTsukimi** [eisbehr-/jquery.lazy#106]
Hi! I'm having trouble getting this to work with dynamically loaded content (in my case, the Infinite Scroll plugin). I tried calling it again on on a $(document).ajaxComplete event (which DOES NOT fire with Inifnite Scroll somehow) and a XMLHttpRequest.prototype.open listener (which DOES fire with Infinite Scroll), but Lazy does nothing upon getting called again.

Code is as follows :

```javascript
function doLazyLoad() {
	$(".lazy, .gridBlock > .background .image").lazy({
		effect: "fadeIn",
		threshold: 300,
		visibleOnly: true,
		onError: function(element) {
			console.log('[LAZY] Error processing element :');
			console.log(element);
		}
	});
}

(function() {
	var origOpen = XMLHttpRequest.prototype.open;
	XMLHttpRequest.prototype.open = function() {
		//AJAX request started
		this.addEventListener('load', function() {
			//AJAX request completed
			console.log('ajax request completed');
			doLazyLoad();
		});
		origOpen.apply(this, arguments);
	};
})();
```

**Comment by eisbehr-** [comment]
You will need to add the config parameter `bind: 'event'`, to tell Lazy that it's not executed on window load. That should do the trick for you.

https://github.com/eisbehr-/jquery.lazy#configuration-parameters

**Comment by AzmaTsukimi** [comment]
OK, that was dumb. I was hooked on the end of the AJAX request, at which point the new content hasn't been appended yet. I guess leaving this here might help.
