### ISSUE TITLE
Error make me crazy - On it has this happened to you?

### ISSUE THREAD

**Issue by jcnavamorffe** [eisbehr-/jquery.lazy#107]
In the Lazy Plugin has this happened to you?

![captura de pantalla_2017-09-19_11-15-57](https://user-images.githubusercontent.com/11263629/30585094-01701a08-9d2c-11e7-9c17-6e9bd7d6c424.png)

**Comment by jcnavamorffe** [comment]
somebody?

**Comment by eisbehr-** [comment]
Hello @jcnavamorffe !

It is impossible to help you without more details. Just a screenshot don't tell about your setup and configuration. So please create a jsfiddle recreating the problem and I will take a look.
