### ISSUE TITLE
image not loading when on local file system (file:///)

### ISSUE THREAD

**Issue by sdalu** [eisbehr-/jquery.lazy#109]
lazy doesn't  work when the image to be loaded is on the local file system

**Comment by eisbehr-** [comment]
**Don't ever use `file:///` resources!** Why do you even have the idea to do so? Just **don't**!
It's even permitted by the most browser techniques (_like JS_) in general. That's why it don't work.

**Comment by sdalu** [comment]
It's because all the resources are on the file system. 
It's a locally generated documentation but with tons of pictures and that's too much for the browser to load them at once

**Comment by eisbehr-** [comment]
You don't need to explain yourself, it's still technially impossible to load `file:///` resources with JS. So there is still no way. But as asked before, why would you even do this? Just put the images in a sub-folder of your document or something and just use a relative file path. Even possible in parent folders with `../`. Then you could use Lazy and don't use such like file references ...

**Comment by sdalu** [comment]
Perhaps I shouldn't have put file:/// in the title (as it's only used for loading the main document). 
Inside the document it's already all relative path and Lazy it's not working

**Comment by eisbehr-** [comment]
Then you did something wrong. If you use relative images it works even if you load the main document with ``file:///`. You must have an error anywhere else in your code. Hard to tell without access or an example.
