### ISSUE TITLE
Lazy load responsive images

### ISSUE THREAD

**Issue by ltduc** [eisbehr-/jquery.lazy#111]
Hi, Team!

I need responsive images by width, ex: 

img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-src="image1.png" alt="" class="lazy img-responsive"
                 data-srcset="image1.png 280.5w, image2.png 400w, image1.png 600w" data-sizes="600vw"

Please help me!

Thanks!

**Comment by eisbehr-** [comment]
Just keep your eyes open. ;)
http://jquery.eisbehr.de/lazy/example_use-srcset-and-sizes

**Comment by ltduc** [comment]
Hi, Eisbehr!

http://jquery.eisbehr.de/lazy/example_use-srcset-and-sizes: 
Ex: <img class="lazy" data-src="1x.jpg" data-srcset="1x.jpg 1x, 2x.jpg 2x, 3x.jpg 3x" data-sizes="700vw" />

I understand 1x, 2x, 3x is **device resolution** but i want set **by width any** ex: image1.png 280.5px, image2.png 400px, image1.png 600px

Like: https://github.com/verlok/lazyload
Responsive images - srcset and sizes
<img data-src="/your/image1.jpg"
    data-srcset="/your/image1.jpg 200w, /your/image1@2x.jpg 400w"
    sizes="(min-width: 20em) 35vw, 100vw">

Please, Help for me!

Thanks!

**Comment by eisbehr-** [comment]
I think you understand something completely wrong. `srcset` is default html attribute for `img` tags. That has nothing to do with such lazy loading libraries. Lazy just _supports_ `srcset`, but not invented it on it's own. You can search the net for details about the possibilities of [`srcset`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset) and [`sizes`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-sizes).

**Comment by ltduc** [comment]
Hi, Eisbehr!

I understand wrong about srcset and sizes.

Thanks for help to me!
