### ISSUE TITLE
Lazy load skip images invisible

### ISSUE THREAD

**Issue by ltduc** [eisbehr-/jquery.lazy#112]
H, Eisbehr!

I use lib https://owlcarousel2.github.io/OwlCarousel2/ with jquery.lazy:
+ Total items: 10 item
+  $("#slide").owlCarousel({
        margin: 10,
        loop: true,
        items: 1
})

but last images invisible doesn't load when i swiper.

Please, Help for me!

Thanks!

**Comment by eisbehr-** [comment]
You need to think about how scripts work. Lazy loads images on `scroll`. But the slider uses it's own events for sliding images. So you need to tell the slider to load images with lazy on swipe. Therefore you could use the [public function](https://github.com/eisbehr-/jquery.lazy#instances-and-public-functions) `update` of Lazy, which needs to be executed on slide. That can be done by a callback of the slider.

Beside that, Owl Carousel has an own [plugin for lazy loading](https://owlcarousel2.github.io/OwlCarousel2/demos/lazyLoad.html) the slider, what could be an alternative too.

**Comment by ltduc** [comment]
Thanks, Eisbehr!
