### ISSUE TITLE
Lazy AdSense?

### ISSUE THREAD

**Issue by wzol** [eisbehr-/jquery.lazy#114]
I'm trying to lazyload AdSense ads - only load them if visible - using the script plugin, but can't make it work. I've tried this, but it doesn't load:

`<script data-src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
			<ins class="adsbygoogle"
				 style="display:block"
				 data-ad-client="ca-pub-XXXXXXXXXXXXX"
				 data-ad-slot="XXXXXXXXXXXXX"
				 data-ad-format="auto"></ins>
			<script>
			(adsbygoogle = window.adsbygoogle || []).push({});
			</script>`

**Comment by eisbehr-** [comment]
Hello @wzol 

I'm sorry, but I don't have any experience with AdSence and it's integrations. So I can't help you any further. I'm not sure if and how these could be lazy loaded.
