### ISSUE TITLE
getting .Lazy() is not a function

### ISSUE THREAD

**Issue by gt06** [eisbehr-/jquery.lazy#115]
I have implemented it in magento project. I got jQuery.Lazy() is not a function.

I am not getting how to solve this.

**Comment by eisbehr-** [comment]
Hello @gt06 

And how do you think I should help you now?

Sounds like you did something wrong there. This is not a problem related to the plugins itself. Beside this, you seem to think I have some kind of magical powers, so I would know your problem without any details and sources. 😉

**Comment by gt06** [comment]
I have implemented it in magento project. I got jQuery.Lazy() is not a function error.

I am not getting how to solve this.

<img class="lazy" srcset="images/1.jpg" data-src="images/1.jpg" />
<img class="lazy" srcset="images/2.jpg" data-src="images/2.jpg" />

I have also added thises two lines into my project.

<script type="text/javascript" src="jquery.lazy.min.js"></script>
<script type="text/javascript" src="jquery.lazy.plugins.min.js"></script>

initialization:

jQuery('.lazy').Lazy();

**Comment by eisbehr-** [comment]
Are you sure jQuery is there too?
And are you sure the path to the Lazy files is correct?
And what is the original error message you got?

**Comment by gt06** [comment]
jQuery(...).Lazy is not a function this is error i am getting.

HTML - 
<img class="lazy" srcset="images/1.jpg" data-src="images/1.jpg" />
<img class="lazy" srcset="images/2.jpg" data-src="images/2.jpg" />

js -

jQuery('.lazy').Lazy();

**Comment by eisbehr-** [comment]
Sorry, I don't see any problem here. As I asked before, make sure jQuery is available before you load the Lazy script files. And make sure the path to files is correct too. Everything else looks okay.

**Comment by gt06** [comment]
```
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script src="js/src/jquery.lazy.js"></script>
<script src="js/src/jquery.lazy.plugins.js"></script>

```
I have already added jQuery before loading lazy scripts.
Also the images path are correct with class name lazy.

It would be better if you help me.

**Comment by eisbehr-** [comment]
There is no problem I could help you with. And as you [see here](https://jsfiddle.net/sLhwt8s8/), there is no problem with it in general. So there is something else wrong on your side ...
