### ISSUE TITLE
Chrome has freezed when loadAll images

### ISSUE THREAD

**Issue by elpablos** [eisbehr-/jquery.lazy#116]
Hi there!
I have very complex web application which downloading async document into website and then download bunch of images via jquery.lazy.
It's necessary to load it all together because I need calculate how long is the document after render of pictures.
So I used this:
`
            $(".lazy").lazy({
                bind: "event",
                delay: 0
            });
`
Troubles appears only in Chrome when after load of images just freeze and only way how to run it again is kill process in TaskManager.
I spent 3 days of founding solution and I have found that problem is in frequently update of DOM.
My solution is comment or delete row 483 in jquery.lazy.js:
`
                    // bring it back with some effect!
                    // element[config.effect](config.effectTime); // comment this
`
And show all images at once in event onFinished.
`
            $(".lazy").lazy({
                onFinishedAll: function () {
                    $(".lazy").show();
                },
                bind: "event",
                delay: 0
            });
`

I hope that it helps somebody!
Elpablos

**Comment by eisbehr-** [comment]
Hello @elpablos 

Thanks for your report. This is a interesting thing. What happens if you replace the out commented part `element[config.effect](config.effectTime);` with just `$(".lazy").show();`, does this change anything?

Is there any way you could recreate the problem in a [js fiddle](https://jsfiddle.net)? Not the whole thing just the amount of images loading at once, that your Chrome freezes too? I could try to find a solution then.

**Comment by eisbehr-** [comment]
No further input from @elpablos 
Can't help ...

**Comment by elpablos** [comment]
Hello @eisbehr- ,
sorry for lately response, I forgot about it because I have alot of works.

I actually don't need help, I wrote it because I've found this issue and I was thinking that it was fine to write down for another users. 

It's very specific problem because I used lazy plugin but I need to load it at once because of size calculation (it's actually eBook reader and it loads content on-the-fly but I must calculate number of pages).

> Thanks for your report. This is a interesting thing. What happens if you replace the out commented part `element[config.effect](config.effectTime);` with just `$(".lazy").show();`, does this change anything?

There is no trouble about this part of code. It works well but if you have very complex website with large DOM it has performance effect because you update DOM for example 50 times at once.

If plugin loads images, at first it hide image object - good for DOM
And after load it show it again - good for non-complex DOM

I've changed it to show all images in onFinishedAll event because it update DOM only once and it's better performance solution. 

> Is there any way you could recreate the problem in a js fiddle? Not the whole thing just the amount of images loading at once, that your Chrome freezes too? I could try to find a solution then.

Like I said its very complex website with async loading of chapters from eBooks also with amount of images (~30-50). I will take amount of time to recreate it in js fiddle. 

The only thing what you can do is put switch param (boolean) into plugin with using effect (show) after it loads all.

But keep it close, may be if someone google this specific problem, they can find this article :-)

Thank you and have a nice day!
elpablos

**Comment by eisbehr-** [comment]
Just a quick another hint. How about to use a [custom loader](https://github.com/eisbehr-/jquery.lazy#custom-content-loaders) with Lazy? With this you don't have to edit the plugin files and stay compatible on updates, but you can implement the handling on your own?

As it sounds like you only want to load images instantly it could be pretty straight forward.

```html
<img class="lazy" data-loader="noEffect" data-src="path/to/image_to_load.jpg" src="" />
```

```js
$(".lazy").Lazy({
    noEffect: function(element, response) {
        var imageObj = $(new Image());

        imageObj.one('error',function() {
            response(false);
        })
        .one('load', function() {
            element.attr('src', imageObj.attr('src'));
            imageObj.remove();
            response(true);
        })
        .attr('src', element.data('src'));

        // call after load even on cached image
        imageObj.complete && imageObj.trigger('load');
    }
});
```

If you only want to load the images without any error control, you could write it even more simple. This would even strip down the load any further.

```js
$(".lazy").Lazy({
    noEffect: function(element, response) {
        element.attr('src', element.data('src'));
        response(true);
    }
});
```

**Comment by elpablos** [comment]
It's necessary to fire **onFinishedAll** event which I need to recalculate pages.
The second one freeze Chrome too because of DOM, so it's necessary to hide elements and show it after all.
Could you help me how to fire **onFinishedAll* from custom loader?

Thanks, 
elpablos

**Comment by eisbehr-** [comment]
No problem, `onFinishedAll` will be triggered as usual with both custom loaders. Only thing necessary for this, is that your loader eigther call `response(true)` or `response(false)` as result. This tells lazy that the element was loaded successfully or not. So the second custom loader, you only can't use `onError`, this will be ignored.

If you need to hide an show the elements too, you have to use the _bigger_ solution, because you need the handling for this.

```JS
$(".lazy").Lazy({
    noEffect: function(element, response) {
        var imageObj = $(new Image());

        imageObj.one('error',function() {
            response(false);
        })
        .one('load', function() {
            element.attr('src', imageObj.attr('src')).show();
            imageObj.remove();
            response(true);
        });

        element.hide();
        imageObj.attr('src', element.data('src'));

        // call after load even on cached image
        imageObj.complete && imageObj.trigger('load');
    }
});
```

**Comment by elpablos** [comment]
Thanks!

This in final working piece of code. I've remove show because of freezing Chrome and put it on **onFinishedAll**.
The reason why at first try didn't event raise was that I comment out bind and delay :-)

```
$(".lazy").lazy({
    bind: "event",
    delay: 0,
    onFinishedAll: function () {
        $(".lazy").show();
        // do recalculating and so on
    },
    noEffect: function(element, response) {
        var imageObj = $(new Image());

        imageObj.one('error',function() {
            response(false);
        })
        .one('load', function() {
            element.attr('src', imageObj.attr('src'));
            imageObj.remove();
            response(true);
        });

        element.hide();
        imageObj.attr('src', element.data('src'));

        // call after load even on cached image
        imageObj.complete && imageObj.trigger('load');
    },
});
```

Thank you!
Have a nice day
elpablos

**Comment by eisbehr-** [comment]
Glad we've found a working soloution for your project!
