### ISSUE TITLE
Lazy not functional for jquery v3.2.1 but ok for  jquery2.2.4

### ISSUE THREAD

**Issue by Sheydon** [eisbehr-/jquery.lazy#118]
After updating to v3.2.1 I lost Lazy working but when I go back to jquery2.2.4 it is o.k. ? Using a simple custom loader for a div.

```JS
$(function() {
    $('.lazy').lazy({
        // loads instantly
        lazyload: function(element) {
            element.load();
        },      
    });
});
```

**Comment by eisbehr-** [comment]
Hello @Sheydon 

I [don't have any problems](https://jsfiddle.net/Lsegr927/) with your example and jQuery 3.2.1. Is there any error in console?
It would be nice if you could create a jsfiddle, recreating the issue. I would investigate then.

Thanks

**Comment by eisbehr-** [comment]
Closed because of missing input.
