### ISSUE TITLE
Picture Loader Plugin

### ISSUE THREAD

**Issue by Viggoleinen** [eisbehr-/jquery.lazy#119]
I have problems using the picture loader plugin. The plugin seems to fail loading the default image (it adds "null" to img src).

Here is my code:

```
<picture class="lazy" data-src="default.jpg" data-srcset="small.jpg" data-media="(max-width: 767px)" data-type="image/jpeg" />
```

This the result:

```
<picture class="lazy" data-loader="pic">
<source media="(max-width: 767px)" type="image/jpeg" srcset="small.jpg">
<img src="nulldefault.jpg">
</picture>
```

What I'm I doing wrong? Thanks!

**Comment by eisbehr-** [comment]
That could be a bug I think. Could test to set the config parameter `imageBase` to `''` (empty string) and test if the problem remains?
I will investigate on this issue as soon as I got time.

**Comment by eisbehr-** [comment]
There really was an issue with `imageBase` in the picture plugin. I've fixed this in version `1.7.7`. Thanks for your report.

**Comment by Viggoleinen** [comment]
I can confirm that this is now working!

Another issue is that I can't get the fadein effect to work on my code (works great when only using img and not the picture element):

`<picture class="lazy" data-src="default.jpg" data-srcset="small.jpg" data-media="(max-width: 767px)" data-type="image/jpeg" />`

My settings:

scrollDirection: 'vertical',
effect: "fadeIn",
effectTime: 500,
threshold: 0,
visibleOnly: true

**Comment by eisbehr-** [comment]
That belongs to the fact, that plugins not support all features of the original lazy. If you want to have an fade in effect for picture, just do it on your own in use with the callbacks. It's pretty easy, see [this example](https://jsfiddle.net/6m362Lbj/).

**Comment by Viggoleinen** [comment]
Thank you for your speedy reply and great support. It works great!

I'm using the picture element in order to show one picture for small
devices and another picture for larger devices. Each of those two pictures
have standard and high resolution. Is this the right way to do it?

  <picture class="lazy">
    <data-src media="(max-width:767px)" type="image/png"
srcset="small_device.png 1x, small_device@2x.png 2x"></data-src>
    <data-src media="(min-width:768px)" type="image/png"
srcset="default_device.png 1x, default_device@2x.png 2x"></data-src>
    <data-img src="default_device.png"></data-img>
  </picture>

**Comment by eisbehr-** [comment]
Well, yes. There are many different ways, there is no _right_ way. If this works for you, it great!

**Comment by Viggoleinen** [comment]
Hi! Is there any way of using media queries for lazy loading of background images?
I need to load one background image for small devices and one for large devices (and each one of those has one high-resolution version).

**Comment by eisbehr-** [comment]
Not build in with Lazy. Media queries are pure css and can't be controllt in any other way. So what you can do is to use a custom loader or the callbacks and do it on your own. There are plenty ways as workaround.

**Comment by Viggoleinen** [comment]
OK, I see! May I ask for an example of that? :)

**Comment by BlackStar1991** [comment]
Thank you for your plugin.  Can you help me with the correct plug-in connection for the tag picture ?
`<picture class="bl_games__image">
                                    <source srcset="image/slot-games/big.webp" type="image/webp">
                                    <source media="(min-width: 2400px)" srcset="image/slot-games/big_image.jpg">
                                    <source srcset="middle.jpg">
                                    <img src="middle.jpg" alt="myImage">
</picture>`
How to make a method call correctly so that this plugin worked on all browser permissions? 
What should the javaScript code and html look like so that a simple image be given by default?

**Comment by eisbehr-** [comment]
@BlackStar1991 The whole process and the plugin is well documented. You will get it by yourself. ;)
