### ISSUE TITLE
image  xlink:href

### ISSUE THREAD

**Issue by MohaStudio** [eisbehr-/jquery.lazy#121]
I'm using Image tag & the link of image as  xlink:href:="<imagelink>" for layout matter. 
I'm trying to find away to implement lazy load on such element , any help ?

**Comment by eisbehr-** [comment]
Hello @MohaStudio 

the attribute `xlink:href:` is deprecated and will be removed from the browsers in the future. You should really change your source. https://developer.mozilla.org/de/docs/Web/SVG/Attribute/xlink:href

But in general, you can set the used attribute by the `attribute` config parameter. See [this example](https://jsfiddle.net/5t5gmLa5/).
