### ISSUE TITLE
iPad: "afterLoad"-Event firing too early

### ISSUE THREAD

**Issue by anm12** [eisbehr-/jquery.lazy#122]
I am using jquery.lazy in the newest version to view pictures of a document. In _afterLoad_ I calculate the width and height of the image using _naturalWidth_ and _naturalHeight_. Works fine, but with troubles on iPad/iPhone.

On iPad and iPhone the event seems to be fired too early. _naturalWidth_ and _naturalHeight_ are 0. I added another load-event: 
`element.load(function() {
  applyZoomAfterLoad();
});`

With adding this event-listener, it works perfect, the properties can be read on iPad too.

Is there a possibility to improve this in jquery.lazy? If you need somebody for testing on iOS, please feel free to contact me.

**Comment by eisbehr-** [comment]
Hello @anm12,

well, this is a classic race condition I think. You should not mix up `afterLoad` callback with the `load` event of images. The `afterLoad` is fired after Lazy has done it's work to load the image in background, but not the load of the element. In your case, the problem seems, that the DOM is updated a bit slower than on other devices, what causes the problem.

Just a quick idea to solve this issue: put your `load` event listener in the `beforeLoad` event. So, you register your event by yourself and this should be triggered after load. Like this (not tested):

```JS
$('img').lazy({
    beforeLoad: function(element) {
        element.one('load', function() {
            applyZoomAfterLoad();
        });
    }
});
```

**Comment by anm12** [comment]
Hi Daniel,

I tried your suggested solution, but if I bind the event on _beforeLoad_ it get's triggered earlier than the _afterLoad_ of jquery.lazy. The only working solution at the moment is to bin the load-event in the _afterLoad_ of your component.

Offtopic: Danke für die schnelle Antwort, trotz "Baustress" :)

**Comment by eisbehr-** [comment]
Thats really interesting. I took a look to the source again, and I would not know, why the `naturalWidth` should return zero. It really seems to be a problem of the browser, not updating the properties just in time after load. Maybe iOS is waiting for JS to execute, before updating the DOM object properties. But it's just a idea.

Out of curiosity, is normal `width` return any value at this point?
And just of a test, is somthing like this working:

```JS
$('img').lazy({
    afterLoad: function(element) {
        setTimeout(function() {
            applyZoomAfterLoad();
        }, 1);
    }
});
```

I currently would not know any other solution. But if binding a `load` listener in `afterLoad` works for you, this would be fine too, or not?

Kein Problem! :wink:

**Comment by anm12** [comment]
`width` returns also zero at this place. I also tested, if `naturalWidth` works on iPad with a jsfiddle - there are no problems with that property. Also interesting - `complete`-Property is set to `false`. Waiting for completion is not working properly, the property is not set within `afterLoad`.

Setting a timeout of 1ms does not work.

For me the solution with binding a `load`-Listener in `afterLoad` is OK, but I think it's a good thing to discuss about it, because others will get troubles with iOS too, if they process some things in `afterLoad`. :)

**Comment by eisbehr-** [comment]
`complete` is nothing `afterLoad` or Lazy will set, this is a browser feature too. So in general, this really seems a browser problem updating the properties. There is no way I could force the browser to update this data. So I'm happy we're got a workaround for you!

**Comment by anm12** [comment]
Yes, it is a browser-feature, it is available in safari/chrome on iOS too.  But it isn't set correctly. So I use my workaround - other users are informed too :)

**Comment by eisbehr-** [comment]
Yes, I only wanted to say, that this in no problem of Lazy here, it's a general problem of the browser then. Just for intormation too. ;)
