### ISSUE TITLE
Reload elements if scroll back.

### ISSUE THREAD

**Issue by kuyeduwu** [eisbehr-/jquery.lazy#123]
Is it possible to release elements which are out of visible area due to scroll up / down, and then reload them once scroll into the view?

Saying release element I mean make them unload on page.

I'm working on a project which need to load thousands of elements, I want to make only the visible element loaded, and unload them once they out of view.

Thanks.

**Comment by eisbehr-** [comment]
Hello @kuyeduwu,

as far as I know, there is no _real_ unload for images/elements. You can remove the element or the value of `src` attribute of the element, but the image will be stay loaded in the browser session. So this would not improve anything.

Beside this, your case would be a really, really rare one. So you should implement this on your own. Maybe wirh a custom loader or plugin. But this could be tricky.

Best of luck!

**Comment by kuyeduwu** [comment]
Hello @eisbehr- 

Thank you for your timely reply, actually I had implemented a little which could empty the element, but got a problem that when I scroll back, the content of the element won't be loaded automatically.

I noticed that there are two Attributes called `handledName` and `loadedName`, but have no idea about how to use them, also not sure if they can do any help on this, do you have any suggestions or hints on how to reload the elements?

**Comment by eisbehr-** [comment]
I think the problem here is, that Lazy handle each element only once. So after the first load, Lazy will remove the element from it's own queue. So you would need to add elements, you've removed, back to Lazy again. Therefor you can use the public function of Lazy, in this case `addItems`.

**Comment by kuyeduwu** [comment]
I will have a try, thank you :)
