### ISSUE TITLE
Can I speed up changing tags?

### ISSUE THREAD

**Issue by SilencerWeb** [eisbehr-/jquery.lazy#125]
Hello!

I have a problem with speed of changing tags with a plugin for tag picture. Now it takes about 3 seconds for changing all tags. Can I do it immediately when page is ready? And can I get an event when all tags are changed?

**Comment by eisbehr-** [comment]
Hello @SilencerWeb,

I really don't have an idea what you want to explain. What do you mean with _changing tag_? Please provide an example what you want to do and explain your problem. Otherwise I think I'm not able to help you.

**Comment by SilencerWeb** [comment]
As you know, picture plugin will convert this code
`<picture>
            <data-src media="(max-width: 767px)" srcset="images/image3.jpg"></data-src>
            <data-src media="(max-width: 1279px)" srcset="images/image3.jpg"></data-src>
            <data-src media="(min-width: 1280px)" srcset="images/image3.jpg, images/image3.jpg 2x"></data-src>
            <data-img src="images/image3.jpg" alt="alt"></data-img>
</picture>`

to

`<picture>
            <source media="(max-width: 767px)" srcset="images/image3.jpg"></data-src>
            <source media="(max-width: 1279px)" srcset="images/image3.jpg"></data-src>
            <source media="(min-width: 1280px)" srcset="images/image3.jpg, images/image3.jpg 2x"></data-src>
            <img src="images/image3.jpg" alt="alt"></data-img>
</picture>`

Also, I have a slider on my website and it contains such pictures. When slider is inited, I need to get width of the image(`img`) in the active slide, but I can't because picture plugin didn't have time to change tags.

[Here is a link to the website.](http://silencer.website/tomatdesign/one-project.html)

**Comment by eisbehr-** [comment]
Well, is it possible that you don't understand the consequences of lazy loading? The descriped behavior is exactly what I would expect?! I can't see any problem here or on your page. Maybe I still don't get it, but actually it seems to work ...

**Comment by SilencerWeb** [comment]
Yeah, I already got that it is normal behavior of the plugin.

Sorry for stupid issue and thank you for such great plugin :)
