### ISSUE TITLE
attr on undefined

### ISSUE THREAD

**Issue by roberteventival** [eisbehr-/jquery.lazy#126]
```
 imageObj.attr(_sizes, element.attr(sizesAttribute))
                        .attr(_srcset, element.attr(srcsetAttribute))
                        .attr(_src, imageSrc ? imageBase + imageSrc : null);
```

`element.attr` is resolved to undefined, hence final expression is empty string. Subsequent call of .attr on string does not work. jquery.lazy.js line 500.

**Comment by eisbehr-** [comment]
Would it be possible to give me more information about this issue? Your post has not much details. Best would be, if you could create a jsfiddle reproducing the problem. I would investigate then.

**Comment by eisbehr-** [comment]
Sadly no response till now. Can't recreate any issue.

**Comment by roberteventival** [comment]
sorry for late response, I think you can leave it closed. 
The issue is with `element.attr(srcsetAttribute)` we do not use `srcset`, but jquery 1.7 it returns undefined and thus the fist call returns str causing exception for the second `attr` call.
