### ISSUE TITLE
How to make this plugin to work with Isotope?

### ISSUE THREAD

**Issue by Siilionu** [eisbehr-/jquery.lazy#127]
Hi

How to make this plugin to work with Isotope (https://github.com/metafizzy/isotope)? I created an example but it does not work properly. Overlapping images + filter not showing all images.

Fiddle example: https://jsfiddle.net/a94ed80L/5/

I hope someone knows how to fix it.
Thank you.

**Comment by eisbehr-** [comment]
Hello @Siilionu,

the problem seems to be, that isotope don't know the correct image dimensions. But actually I don't know the isotope, so I can't help you here ... Maybe ask the developer of the tool,how you could add lazy loading.

**Comment by Siilionu** [comment]
Hi, eisbehr

Thank you for the answer. You are right. Isotope don't know the correct image dimensions. Due to the responsive design, images can not contain fixed dimensions. But how to fix that? This is a million dollar question.

I hope someone will notice this issue and finally solves the biggest mystery of the history. :)
