### ISSUE TITLE
Reload Content Ajax

### ISSUE THREAD

**Issue by dungphanxuan** [eisbehr-/jquery.lazy#129]
I load content by Pjax, image will not showing. So how can i reload Lazy

![image](https://user-images.githubusercontent.com/10725732/34809119-92ed0bba-f6c5-11e7-9c91-31418dd83eb5.png)

**Comment by dungphanxuan** [comment]
It's work when i recall again

```php
$(document).on('pjax:success', function() {
     $('.lazy').Lazy();
});
```

**Comment by dungphanxuan** [comment]
Thank for your solution, i will note.

**Comment by dungphanxuan** [comment]
Hi @eisbehr- ,  i have some image slider with BxSlider. How can i use Lazy

![image](https://user-images.githubusercontent.com/10725732/34968447-f3070fc6-fa9b-11e7-800a-ec1ae40b9b8d.png)

**Comment by eisbehr-** [comment]
Lazy only loads images in viewport by scroll for default. So Lazy needs to know whenever new images of the slider hits the viewport. For this you need the [public function](https://github.com/eisbehr-/jquery.lazy#instances-and-public-functions) `.update()` of an Lazy instance. Whenever the slider changes the image, you need to call this function to tell Lazy that there are possible new images in the viewport.

**Comment by pflind** [comment]
@eisbehr- 

Can I run `instance.update();` in a separate javascript file, or do I have to create a new instance?

> ```js
> // javascript.js
> var instance = $('.lazy').Lazy({chainable: false});
> 
> // separate file: ajax.js
> $(document).on('pjax:success', function() {
>     var pjaxElements = $('.loaded-container .lazy');
> 
>     // just add the images to the instance and force an update
>     instance.addItems(pjaxElements);
>     instance.update();
> });
> ```

**Comment by eisbehr-** [comment]
The question is, if you have access to the variable `instance` in your other files. If you have, there is no problem to call `update` there.

**Comment by pflind** [comment]
@eisbehr- 

I did not have access to the variable `instance`, but I solved it this way. Is it the correct way? At least it's working when tested.

**javascript.js:**
```
var instance = ''; // declare global variable

$(function() {
  instance = $('.lazy-load').lazy({ chainable: false });
});

function refresh_lazyload(elements) {
  instance.addItems(elements);
  instance.update();
}
```

**ajax.js:**
```
$(function() {
  $('#autocomplete-search').on('input', function() {
    $.ajax({
      url: 'ajax.php',
      method: "POST",
      data: { keywords: $(this).val() },
      success: function(data) {
        $('ul#autocomplete-content').html(data);
        var lazyelements = $('ul#autocomplete-content .lazy-load');
        refresh_lazyload(lazyelements);
      },
    });
  });
});
```

The only thing I can't figure out is how to use `instance.config(entryName[, newValue]);`

How can I set  `appendScroll: 'ul#autocomplete-content` using `instance.config();` in my `refresh_lazyload();` function?

**Comment by eisbehr-** [comment]
There is not _correct way_, if it's working for you it's fine. :)

Well, if you want to change the elements on witch lazy should listen, you need to destroy the old instance and create a new one. Otherwise the events are not correctly updated.
