### ISSUE TITLE
set image display: none

### ISSUE THREAD

**Issue by mammad2c** [eisbehr-/jquery.lazy#130]
hi, I have this code :

css: 
```
img.lazy-load {
      display: block !important;
      margin: 0 auto;
}
```

js: 
```
$(document).ready(function() {
    var lazyLoad = $(".lazy-load").lazy({
        chainable: false,
        afterLoad: function(elm) {
            $(elm).removeClass("lazy-load");
        }
    });
    window.myLazyLoad = lazyLoad;
});

```

after per image loads, the jquery lazy set its display to none. But if I remove `display: block !important` from the css class the plugin works perfectly. Is it bug? or any solution to remove the specified class?

thanks

**Comment by eisbehr-** [comment]
Sorry, I think I don't get your question?! I see [no problem with your example](https://jsfiddle.net/qaLaqrsc/).
