### ISSUE TITLE
Lazy Loading a Div class, using GTM

### ISSUE THREAD

**Issue by sgpascoe** [eisbehr-/jquery.lazy#135]
I don't have access to the HTML of my page, so my workaround is to use google tag manager. this means I can't change class names or add extra variables to current elements.

The img elements on the page do not have a class, but the div does. 

Is it possible to apply lazy loading to a div class .item, rather than an img?

I've tried:

<script>
    $(function() {
        $('.item').lazy({
          effect: "fadeIn",
          effectTime: 2000,
          threshold: 0
        });
    });
</script>

but this does not work. is this because it is looking for img.item rather than div.item?

**Comment by eisbehr-** [comment]
Can you give me an example of the HTML?

**Comment by sgpascoe** [comment]
Sure - I understand it's a difficult, possibly impossible task :) 


  | <div class="item">
  |  
  | <a href="/linkDestination/" >
  | <div class="productImage">
  | <a class="thumbnail" href="/linkDestination/" title="productNameHere">
  | <noscript><img alt="ProductNameHere" src="/imageDestination/" /></noscript>
  | </a>
  |  
  | </div>
  | <div class="info">  <span class="product-name">productNameHere</span> <span class="price">                           priceHere
  | </span>
  | </div>
  | </a>
  | </div>

**Comment by eisbehr-** [comment]
I don't understand what you want to lazy load in this example? I only see a `noscript` image. And if you can't touch the HTML, where do you place the image that should be lazy loaded?

**Comment by sgpascoe** [comment]
Apologies for my lack of understanding. 

Does a noscript image mean I cannot set javascript/jquery to interact with it (and therefore I cannot lazyload it)?

My aim was to lazy load the enitre div.item, so the page starts smaller on load, and lengthens on scroll. similar to this example from a popular clothing website: http://www.topshop.com/en/tsuk/category/clothing-427

**Comment by eisbehr-** [comment]
No. The `noscript` is fine. I just don't see the normal image you want to load. But beside this, it seems you get something wrong. You can't just add some script and lazy load elements that are already on the page. Everything on your `HTML`, what is already there on page load, is instantly handled. There is no way to lazy load it. What you seems to want to do, is loading content via `AJAX`. But everything of this is impossible, if you can't change your output. So I don't know how to help you in any way...

**Comment by sgpascoe** [comment]
Oh I see - where I wrote  
`<noscript><img alt="ProductNameHere" src="/imageDestination/" /></noscript>`
/imageDestination/  would be the url of the image. 


I see! So using Javascript will not help defer loading of html elements? I need to use AJAX. 

Thankyou very much! I will research AJAX,. Although I cannot touch the code of the site, I will educate myself :) 

Thank you again for your assitance, and for your brilliant lazy loading script. It looks like you've helped a great many people.
