### ISSUE TITLE
Images dont load on PhoneGap iOS until after screen is rotated..

### ISSUE THREAD

**Issue by spinninghamster** [eisbehr-/jquery.lazy#138]
I am trying to get this working with a PhoneGap iOS application. I've also tested it in the browsers (PhoneGap applications can be tested in the browser like web pages) and i'm getting the same behaviour.

The first few images, the ones inside the visible viewport, they load fine. But as I scroll down, the next ones don't show. On an actual iOS device, I can get the next ones to load but only if I rotate the screen. On the browser, I also have the same problem and again can get it to work when I resize the browser window (even if its just 1 pixel).

Any ideas what's causing this?

**Comment by spinninghamster** [comment]
I am starting to suspect this may have to do with the viewport. My configuration is:

`<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=0,viewport-fit=cover">`

I noticed that when I add `threshold: "300"` for example, the jquery.lazy loads **ALL** images (even if they are much further down). If I set no threshold, it loads only the ones visible.

**Comment by kressly** [comment]
I have the same problem on windows phone. Nokia Lumia 635

**Comment by eisbehr-** [comment]
Hello,

it sounds a bit like this devices don't uses `scroll` event on `window` object. As  That's strange, but that is actually the only reason that comes to my mind. If you say turning the screen orientation works means, that `resize` works. So maybe there is problem with `scroll` on iOS/PhoneGap. Maybe it's swipe?! Have no other idea actually ...

**Comment by kressly** [comment]
We can not claim that those devices dont use scroll bcos in my case it does that only for images that have directly a text attached to them. But for images that do not have a text directly close to them it loads the images without rotation required. 

I have a menu where images are attached with a text so the image uses a small space and the text the other space in diverse div. For those one I need to rotate first before I could see the image loading.

However I have other places where I have just images and the text is under them not close to them. For those one I dont need to rotate.

**Comment by eisbehr-** [comment]
Now it will become even more strange! There might be a reason for this, but the plugin don't loads images _sometimes_. So there is something wrong. I would like to investigate on the code. Is there any way I could see/test it?

And do you have this issue only on windows phone, or even on others? As windows phone is generally dead, I don't have access to such device (and would not support it in the future too). But maybe we find the reason that this don't work now.

**Comment by kressly** [comment]
Please support windows phone in the future. Many people where I am are using it to synchronize their windows pc with the phone. For example when you visit this page

https://iusefaith.com/bibles-language-fr-tab-36

on mobile, you will find that the articles under Bibles after the main article when you scroll down, the images there do not show unless you rotate the screen. Only the small images appear.

![wp_ss_20180316_0001](https://user-images.githubusercontent.com/925132/37532164-2d6ed0ae-2936-11e8-89aa-64e464f39862.jpg)
![wp_ss_20180316_0002](https://user-images.githubusercontent.com/925132/37532169-2e00509c-2936-11e8-8694-a9a50d772389.jpg)
![wp_ss_20180316_0003](https://user-images.githubusercontent.com/925132/37532170-2e62e3b0-2936-11e8-92ea-64745d37c6e9.jpg)

**Comment by nattyluke** [comment]
same problem for me too, sometimes its loading, sometimes not, when im scrolling up its usually working, scrolling down doesnt show my image. testet in firefox (phone and developer console)

**Comment by eisbehr-** [comment]
@nattyluke Is it possible that phonegap doesn't trigger the `load` event correctly?! Maybe try the config parameter `bind` set to `event` an detect the loading otherwise in your pages. Or maybe use `update` function after load, because scrolling works this should work too.

Because scrolling in your page works correctly it seems to be just a problem with initialization at the wrong time.
