### ISSUE TITLE
How to use jquery lazy load with ajax ?

### ISSUE THREAD

**Issue by kressly** [eisbehr-/jquery.lazy#139]
When the images are called with ajax they do do not load. Please how to use it with ajax ?
I did  
```
$(function() {
        $('.lazy').lazy({
            placeholder: "data:image/gif;base64,R0lGODlhEALAPQAPzl5uLr9Nrl8e7...",
			effect: "fadeIn",
          effectTime: 2000,
          threshold: 0
        });
    });
```
However it is not working. Sometime back when i had that challenge with Colorbox, the solution was to 
call for body click like 
```
$("body").on("click", ".photos", function(event){
		
	$(".photos").colorbox({rel:'photos', transition:"fade"});
	 
	});
```
But with lazy load there is no body click so even though i did  
```
$(function() {
        $('body .lazy').lazy({
            placeholder: "data:image/gif;base64,R0lGODlhEALAPQAPzl5uLr9Nrl8e7...",
			effect: "fadeIn",
          effectTime: 2000,
          threshold: 0
        });
    });
```

It still does not load when the page is called with ajax. So How to use jquery lazy load with ajax ?

**Comment by eisbehr-** [comment]
Hello @kressly 

plesae think about how jQuery (_and Lazy_) work. There is not kind of _auto detection_ of new elements (_expect somebody build it on its own_). So if you load new elements via AJAX you need to tell jQuery/Lazy that there are new elements.

In case of Lazy, there are some [public functions](https://github.com/eisbehr-/jquery.lazy#instances-and-public-functions) you can use of an Lazy instance. In your case you would need to use `addItems` and `update`.

With `addItems` you can add new elements to an existing instance of Lazy. So the plugin knows that he has to handle these elements too. With `update` you can force Lazy to do a single update of the current viewport, without using `scroll` or `resize` event.

So, that means, you have to slighly update your code.

```JS
var instance = $('.lazy').lazy({
    chainable: false, // tell lazy to return its own instance
    placeholder: "data:image/gif;base64,R0lGODlhEALAPQAPzl5uLr9Nrl8e7...",
    effect: "fadeIn",
    effectTime: 2000,
    threshold: 0
});
```

Afterwards you need to use the two public function, mentioned above, after the AJAX request got finished. I don't know how you load the new elements, but there might be a callback or something where you could execute these.

```JS
instance.addItems('.jquery-selector-for-new-items-only');
instance.update();
```

And thats it ...

**Comment by Quinten** [comment]
I also needed to set `autoDestroy` to `false`.
