### ISSUE TITLE
Responsive images with uknown width / height

### ISSUE THREAD

**Issue by Kcko** [eisbehr-/jquery.lazy#141]
Hi , 
your plugin looks really good. How to solve images in some fluid box (eg bootstrap grid) where i dont know width or height (there are many differenent resolutions, I can´t set fixed position for width / height).

Some elegant solution?

**Comment by Kcko** [comment]
@kressly  absolutely not. You can´t set fixed dimension in responsive design.

**Comment by kressly** [comment]
Actually u can. With bootstrap I set images at a fixed dimension and add the class " img-responsive lazy"

**Comment by Kcko** [comment]
I want to know common solution (not in conjunction with a boostrap, but in general)

**Comment by eisbehr-** [comment]
Hello @Kcko 

Good question. Actually I don't have an concrete answer, beacuse I never personally did this. My first idea would be , to set `min-width` to `1px` and `min-height` as best as possible to the elements. So they have a default dimension. That lazy loading would work in general. For a better match you could even work with media queries to get even more correct sizing of the elements.

Only downside here would be, that is the size is not matching, there might be some more images loaded as necessarry on scroll.

Maybe there are better solution (as using background image for example), but I personally not did this before.

**Comment by Kcko** [comment]
Hi @eisbehr :-),

I found solution.  I prepare a clean demo without plugin and if you want, you can post it.

**Comment by eisbehr-** [comment]
Of course, thank you! 👍

**Comment by Kcko** [comment]
Here it is (my website:  http://lab.rjwebdesign.cz/lazy-with-responsive-images/)
And short video (with 3G slow mode).
The trick is in css "small hack" - set zero height and calculate ratio between image height and width and set padding bottom.

is it a  useful?

**Comment by Kcko** [comment]
Without comment? :/

**Comment by eisbehr-** [comment]
What for a comment do you want? 😉 I closed this because the issue is solved for you. Why to let it open?!

I saw your solution, But this is not a solution for _the mass_. It's more an edge-case and you used `php` to solved this. Nothing I can show here anywehere.

Thank you anyway! 👍

**Comment by mavci** [comment]
How about this @eisbehr- ? I convert @Kcko solution to JS;

```js
$('.lazy').each(function() {
    var split = $(this).data('ratio').split('/');
    var ratio = split[1] / split[0];
    $(this)
        .wrapAll($('<div class="lazy-placeholder"></div>')
        .css('padding-bottom', (ratio * 100) + '%'));
});
```

All you have to do is adding data-ratio attribute to calculate ratio;

```html
<img data-ratio="42/32" class="lazy" data-src="https://picsum.photos/420/320?random">
```

[JSFiddle example](http://jsfiddle.net/xpvt214o/893375/)

**Comment by Kcko** [comment]
@mavci Looks good. I created own tiny plugin, because I need to work with different image sizes on different resolutions. See example: (http://bit.ly/2EsH5eG) What do you think about it?

@eisbehr- developed really awesome plugin, but this option is not included.
