### ISSUE TITLE
Chrome displays a broken image outline when supplied an empty src

### ISSUE THREAD

**Issue by theetrain** [eisbehr-/jquery.lazy#143]
## Defect description 

Test on Chrome and Safari
Demonstration (view in Chrome): https://jsfiddle.net/etrain/r0cefv0a/

Given an HTML image with an empty `src` attribute such as:

```html
<img class="lazy" data-src="./path/to/img.jpg" src="" />
```

The `src` evaluates as `src(unknown)` in Chrome and Safari, which results in a broken image appearance:

![image](https://user-images.githubusercontent.com/12798751/38472838-e2d38cb2-3b53-11e8-857d-8780c9017fc3.png)

I noticed the [effects demonstration](http://jquery.eisbehr.de/lazy/example_make-use-of-effects) does not have this issue due to every images' `src` attribute being supplied a `data:image/gif` value.

## Workaround

I am supplying the value `//:0` to my images' `src` attribute, that way users do not see broken image appearances while the images are being lazy loaded. 

Another workaround is to set `visibility: hidden` to every image and then set them to `visibility: visible` using the `afterLoad` callback.

### 1. Update the documentation

Update the documentation to advise consumers to set their images `src` attribute to an empty MIME type or `//:0` to mitigate this effect

### 2. Hide images until they are loaded

Another idea that works is to advise consumers to supply a `.lazy` class to their images with the following styles:

```css
.lazy {
  visibility: hidden;
}
```

That way there is no broken image appearance before they are loaded, and the `afterLoad` callback can set `visibility: visible`.

**Comment by eisbehr-** [comment]
This has nothing to do with Lazy, it's just because you put a `setTimeout` around it. How should the plugin handles the images if you let it wait two seconds?! That's a selfmade issue. By default Lazy will set an empty/transparent gif to every element without an `src`. This is what the config parameter `defaultImage` is for. So in general you would not need any workaround. And if you want a timeout, you should use the `delay` config parameter. Then Lazy will handle the images but not start loading.

https://jsfiddle.net/r0cefv0a/20/

Maybe take a look to all options: https://github.com/eisbehr-/jquery.lazy#configuration-parameters

Another simple way, if you still want to use a timeout, you could set an empty image to the `src` by yourself. But you should **never** use `visibility: hidden` in this case! This could/would have so many side-effects to the page. May `opacity: 0`, but this is still not needed here.

**Comment by theetrain** [comment]
Thanks for taking the time to respond to my query. My hope was that I was doing something wrong when consuming Lazy. To make my example clearer, I have a page that is loading a large background image and that causes a delay before the `Lazy()` method is executed, especially on slow devices (3G speeds).

I updated my example without using an artificial delay: https://jsfiddle.net/etrain/r0cefv0a/28/

The effect is emphasized when refreshing on a simulating mobile device:

![screen recording 2018-04-09 at 09 43 am](https://user-images.githubusercontent.com/12798751/38501365-d0c693ca-3bda-11e8-9b96-7957238e84a2.gif)

I can see how `visibility: hidden` may lead to consequences I may not be aware of. I believe setting `src` to a MIME type or `//:0` are viable solutions. What do you think?

**Comment by eisbehr-** [comment]
You have a large background image what loads slow? Why not lazy loading it?! 😉 
https://jsfiddle.net/r0cefv0a/33/

**Comment by theetrain** [comment]
Nice! That's definitely an improvement, so I'll keep in mind the benefits of lazy loading all my page's images. Still, the effect is present on slow devices, but is not as pronounced as the non-lazy-loaded background image example. For now, I can still stand to benefit from a default `src` value.

![screen recording 2018-04-09 at 09 58 am](https://user-images.githubusercontent.com/12798751/38502324-109e45fe-3bdd-11e8-845f-5f8b239eab96.gif)

**Comment by eisbehr-** [comment]
That belongs to the amount of files loaded before the execution of Lazy. Maybe this is a bit better for you (executed on dom ready, not after load):
https://jsfiddle.net/r0cefv0a/36/

Other way I would prefer is to set a 1x1 pixel transparent `gif` to all images as default source. Using `//:0` could lead to unnecessarry requests I would prevent. You could even set the base64 image of Lazy to all elements manually, but i think a `blank.gif` is much nicer, even for maintenance.

**Comment by theetrain** [comment]
Thank you, your suggestions are very insightful. If you don't mind, I can contribute to your documentation to help surface this nuance. If you feel this is more of an edge case, then I'll accept your suggestion for just my project.

**Comment by rhyd42** [comment]
I only noticed this when I started adding alt text to my images - the broken icon then showed along with the alt text. If I set src="blank.gif" then the broken icon showed during swapout. Setting img { color:transparent } fixes it for some reason.
