### ISSUE TITLE
Attach to scroll / resize event of container after intialization

### ISSUE THREAD

**Issue by 4BRobby** [eisbehr-/jquery.lazy#144]
First of all great work!

Scenario:
You have multiple lazy loading picture areas, so you might want to initialize them globally:
`$('.lazy').Lazy();`

On the other hand if you have a special area with horizontal scrolling on mobile devices the window.scroll will not work, you have to attach to the container with the lazy images. Like:
`$("#container .lazy").Lazy({appendScroll: $('#container')})`

All will work now. But events for the container are fired twice during intialization and on other occasions.

It would be amazing to have the Lazy instance listening to the scroll event of a container without reinitializing.

Just a detail. I am not sure about how you can approach this though

**Comment by eisbehr-** [comment]
What do you expect, you initialize Lazy twice so why should the events not be fired twice? ;)

You can't do it like this. You need to exclude the `#continaer .lazy` elements from your first initialization. For examples, you initialize all ements, but not the one inside the container. Then afterwards, you can initialize a second instance for the elements inside the `#container`.

```JS
$('.lazy:not(#container *)').Lazy();
$('#container .lazy').Lazy();
```

**Comment by eisbehr-** [comment]
Well, you need different instances to tell Lazy witch elements belongs to witch scroll event. But you can use one global configuration and just change the `appendScroll` paramter? Thats pretty easy.

And I would give all containers a unique class you can use for initialization. With ids you have the problem, that you would need to list all ids in the `:not()` selector.

For example:

```HTML
<img class="lazy" />
<img class="lazy" />
<div class="scroll-container" id="container">
  <img class="lazy" />
  <img class="lazy" />
</div>
<div class="scroll-container" id="container2">
  <img class="lazy" />
  <img class="lazy" />
</div>
<div class="scroll-container" id="container3">
  <img class="lazy" />
  <img class="lazy" />
</div>
```

```JS
// global config
var lazyConfig = {
  effect: 'fadeIn',
  effectTime: 2000,
  threshold: 0
};

$('.lazy:not(.scroll-container *)').Lazy(lazyConfig);
$('#container .lazy').Lazy($.extend({}, lazyConfig, {appendScroll: $('#container')}));
$('#container2 .lazy').Lazy($.extend({}, lazyConfig, {appendScroll: $('#container2')}));
$('#container3 .lazy').Lazy($.extend({}, lazyConfig, {appendScroll: $('#container3')}));
```

Or do the initialization a bit more automatically, if you have an undefined amount of scrollable areas:

```JS
$('.lazy:not(#scroll-container *)').Lazy(lazyConfig);
$('.scroll-container').each(function() {
    $('.lazy', $(this)).Lazy($.extend({}, lazyConfig, {appendScroll: $(this)}));
});
```

That is untested and just my idea, but this might give you some ideas how you could possible do it.

**Comment by 4BRobby** [comment]
I wanted to avoid global config vars and horizontal containers having a special name pattern to avoid initializing them from the central JS but I will give it a try this way with a class like horizontal-scroll-container  (centralized JS general initializing and on-page if needed special container attached initialization). Your hint gives a nice idea how it can be done.

I will close this for now and would like to thank you for your time and input!
