### ISSUE TITLE
Duplicate download (src and srcset

### ISSUE THREAD

**Issue by Kcko** [eisbehr-/jquery.lazy#146]
Hi,  here is my code.

When I am under 800px (on phone) I expected that browser download only img-800.png and img-3000.png if not.

How it is possible?

On small screen iit does not respect the conditions.

		<div class="slide lazy" 
			style="background-position: center; background-size: cover; background-repeat: no-repeat;"
			data-src="img-3000.png"
      data-srcset="img-3000.png 3000w, img-800.png 800w"
			>

See video pls: https://goo.gl/mKruVe

**Comment by eisbehr-** [comment]
`srcset` can only be applied to `img` tags and will not help you on other elements.
