### ISSUE TITLE
Error from latest version

### ISSUE THREAD

**Issue by cluwong** [eisbehr-/jquery.lazy#148]
Updated to V1.7.8 and get the following error:
jquery.lazy.plugins.min.js:2 Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at a (jquery.lazy.plugins.min.js:2)
    at LazyPlugin.<anonymous> (jquery.lazy.plugins.min.js:2)
    at _triggerCallback (jquery.lazy.js:657)
    at _handleItem (jquery.lazy.js:446)
    at _lazyLoadItems (jquery.lazy.js:369)
    at _initialize (jquery.lazy.js:251)
    at dispatch (jquery.js:5206)
    at elemData.handle (jquery.js:5014)

Using jQuery 3.2.1.

Content is loaded via AJAX.

Let me know if you need more info.

**Comment by eisbehr-** [comment]
Hello @cluwong 

okay, I see. There might be a problem in the AJAX plugin. To verify the reason, could you  show me the html of your elements and the initialization of Lazy? I will fix this then. 

Thank you!

**Comment by cluwong** [comment]
Code as follows:
```
<div class="card-block ">
    <div class="widget-wrapper lazy" data-loader="ajax" data-src="https://...">
        <div class="loading"></div>
    </div>
</div>
```
`$('.lazy').lazy();`

**Comment by eisbehr-** [comment]
Ah, yes, as I expected. I will fix this!

**Comment by eisbehr-** [comment]
Fixed!

**Comment by cluwong** [comment]
Thanks. It's now working.
