### ISSUE TITLE
How to Integrate with OwlCarousel 2.3.4

### ISSUE THREAD

**Issue by vishy93** [eisbehr-/jquery.lazy#149]
Although OwlCarousel incorporates lazy loading it does don't have in viewport support. Thus, would like to use this plugin alongside OwlCarousel. 

Now, when I try to use this plugin with OwlCarousel I am faced with some issues that I cannot gather how to solve so was wondering if a kind soul could help.

The main slider on top is bizarrely expanded past the height of the image. Resizing browser window will fix it, but on load it is far too big in height.

Likewise, the carousel below when I scroll to it, it will load from image 1 to 6 even though 5 and 6 are not in view. 

Please see [pen](https://codepen.io/vishpatel93/pen/VxQqXx) for example.

**Comment by avg0043** [comment]
I'm having same problem :(

**Comment by vishy93** [comment]
Hope someone can help

**Comment by eisbehr-** [comment]
Hello @vishy93

Isn't that nearly the same question, you asked some time ago? The key is to integrate Lazy with the callbacks of the carousel. You basically need to tell Lazy when to run an update and load the images. Therefore you can use the events of OC. 

Maybe take a look to the old example. This might point you in the right direction.
https://github.com/eisbehr-/jquery.lazy/issues/140

As I don't know and use this carousel on my own, I can't help you any further. But the callbacks should do the trick. Good luck!

**Comment by vishy93** [comment]
@eisbehr- I appreciate the response. I understand the need to call update callbacks etc.

But, this is different question in that it is the functionality not behaving how one would expect. Maybe a question more suitable for OWL Carousel. It's just that using this plugin causes the main slideshows height to be irregularly expanded, even though this plugin does not as far as I am aware affect the height in any way.

Moreover, even though the threshold is set to 0, I can see images of the carousel not in view yet being loaded.

**Comment by eisbehr-** [comment]
Pretty sure the problem belongs to the fact, that the carousel can't determine the dimensions because the elements are not loaded. Maybe you need to call an update of the carousel too after lazy initialization. But that's just a idea ...

**Comment by vishy93** [comment]
@avg0043 Have you been able to do further debugging?

**Comment by vishy93** [comment]
@eisbehr- I have also noticed noticed that it lazy loads the last image of the slideshow first
