### ISSUE TITLE
Use 'fadeTo' effect

### ISSUE THREAD

**Issue by BernhardWebstudio** [eisbehr-/jquery.lazy#150]
Thanks for this awesome project!
I have a question regarding the effects. I do have a placeholder generated by [sqip](https://github.com/technopagan/sqip). As it resembles the final image rather good, I would like to have it transition smoothly, possibly with the 'fadeTo' effect by jquery. Unfortunately, this effect leads to an invisible image. The effect 'show' leads to a squeezed image and 'fadeIn' to a white flash before the real image fades in. Is there a way to achive the desired transition using this library?

**Comment by eisbehr-** [comment]
Hello @BernhardWebstudio 

I would suggest to use `beforeLoad` and `afterLoad` callbacks to implement this on your own. This should be pretty easy to do in general.
