### ISSUE TITLE
Some images are not loading on mobile

### ISSUE THREAD

**Issue by xbiggyl** [eisbehr-/jquery.lazy#151]
I've been trying to figure out why this is issue is happening for weeks now.
I'm facing the issue on https://www.ofrero.com/

I use the owl carousel plugin to showcase my images and I have implemented lazy load on all the images of the index page.

However, when visiting the page from mobile (tested on android) or by using the mobile perspective in the inspector(chrome), scrolling down to some of the images below, random ones don't load, unless you scroll up or down a few pixels.

Also scrolling horizontally one of the carousel reveals unloaded images, and to force them to load, you just scroll up or down.

Any insight is really appreciated.
Cheers

**Comment by eisbehr-** [comment]
Hello @xbiggyl 

How did you integrate Lazy in your OwlCarousel setup? Lazy don't work with it out of the box and I didn't see any changes by your side. And beside this, you seems to use Lazy and lazy loading of owl carousel itself. Maybe you have a problem in your whole setup.

And just to inform you, I have none loading images even on my desktop client. So you might have a general issue there. But I don't know how to help you. I think you need to clean your whole page ...
