### ISSUE TITLE
strange behaviour with customLoader/ajax plugin

### ISSUE THREAD

**Issue by rudycox** [eisbehr-/jquery.lazy#153]
I have to load more than 2000 items with images. Items data come from mysql, images from folder

My main page loads 50 records and at the end contains some divs like these (till data-start reach the end of records)
data-start: is the offset to start 
data-valore: contains part of the sql (may change)

<div class="lazy" data-loader="ajaxLoader" data-start="51" data-cosa="" data-valore="%20grmer1%20%3D%27013%27%20and%20grmer2%3D%27014%27" data-id="51" id="P_51" style="min-height: 250px;"></div>
<div class="lazy" data-loader="ajaxLoader" data-start="101" data-cosa="" data-valore="%20grmer1%20%3D%27013%27%20and%20grmer2%3D%27014%27" data-id="101" id="P_101" style="min-height: 250px;"></div>

etc ect

when I load the Mainpage  ALL divs are suddenly populated (but this not my goal)
If scroll down ( i.e. to the middle of the document height when populated) and I hit  refresh, all div below the view are suddenly populated, but if I scroll up, upper divs are populated when becomes visible (like it shoul be...but inverted)
I tried with ajaxplugin too but I have axactly the same behaviour

every populated div contains 50 blocks like this (if useful)

```
<div class="col-md-1 col-sm-6" id="prodotti">
<div class="sp-feature-box-3 margin-bottom">
              <div class="img-box"> <a href="prodotto.php?codart=B61590500K&codvar=" class="view-btn uppercase">Dettagli</a>
                 <img class="img-responsive" id="B61590500K" src="/media/img_prod/medium/B61590500K.jpg" />                 </div>
                <div class="clearfix"></div>
                <h6 class="less-mar-1">B61590500K</h6>
              <h6 class="less-mar-1">FORBICI MERCIAIO 5'' cm.12.5 </h6>
              <p>Q.ta/conf: 1 pz<br />
              Prezzo: &#8364; 21,06 / pz<br />
 </p>
              <div class="col-xs-7 prezzi"><h5 class="text-gyellow">&#8364; 21,06</h5></div>
              <div class="col-xs-5 left"><a class="btn btn-border light btn-tiny " href="javascript:void(0);" onclick="prodotto_preaggiungi('B61590500K', '','O');"><i class="fa fa-cart-plus fa-4" aria-hidden="true"></i></a> </div>
              </div>
</div>
<!--end item-->
```
This is js code: 
```
$("div.lazy").lazy({
	delay: 	-1,
	threshold: 0,
	scrollDirection: 'vertical',
        effect: 'fadeIn',
	visibleOnly:true,
     
        ajaxLoader: function(element, response)  {
            $.ajax({
                url: "selezioni/aj_jq_prodotti.php",
                method: "POST",
                dataType: "html",
                data: {
					id: element.data("id"),
					cosa: element.data("cosa"),
					start: element.data("start"),
					valore: escape(element.data("valore"))
						},
                success: function(data) {
					 var mydiv = $(element);
					 mydiv.removeClass('lazy');
	                                 mydiv.html(data);
                                        mydiv.fadeIn(3000);

                                        response(true);
					
				
                },
                error: function() {
                    response(false);
                }
            });
        }
    });	   	
```
Is it a bug o my mistake?

RudyCox

**Comment by rudycox** [comment]
missing divs... sorry 
```

<div class="lazy" data-loader="ajaxLoader" data-start="51" data-cosa="" data-valore="%20grmer1%20%3D%27013%27%20and%20grmer2%3D%27014%27" data-id="51" id="P_51" style="min-height: 250px;"></div>
<div class="lazy" data-loader="ajaxLoader" data-start="101" data-cosa="" data-valore="%20grmer1%20%3D%27013%27%20and%20grmer2%3D%27014%27" data-id="101" id="P_101" style="min-height: 250px;"></div>
etc ect 
```

**Comment by eisbehr-** [comment]
Hello @rudycox 

as far as you described the problem, I'm pretty sure your div's don't have an initial height. Is this possible? Just give the div's some height. If you don't know the exact loaded height, just work with `min-height`. 

And a hint/question: Why do you use `var mydiv = $(element);`? The `element` already is a jQuery object. So you could just write:

`element.removeClass('lazy').html(data).fadeIn(3000);`

**Comment by rudycox** [comment]
Yes divs already have 'style="min-height: 250px;"' (look above).
I think that is a problem related to the  amout of data /css
I solved it using a trick:
at the end of the page - and after all the  lazy divs that are dinamically printed - I print that:
<div id="lastrow"></div>

I put the lazy code above in a function 
function lazyload(){.........}
and using Jquery plugin .onAvailable inside document ready, call that function
$(document).ready(function() {
      $.onAvailable('lastrow', lazyload);
});

now everything seems to work fine

Thankyou for your great job and support.
