### ISSUE TITLE
images don't load when is use swipers

### ISSUE THREAD

**Issue by mojtabakarimi** [eisbehr-/jquery.lazy#154]
First of all, I appreciate your great work.
I really thank you
and ...
Images don't load when is use swipers(http://idangero.us/swiper)
here is the image:
![2018-06-18_19-11-03](https://user-images.githubusercontent.com/38203867/41543454-125186aa-732c-11e8-97e3-12696bc53ced.jpg)

**Comment by eisbehr-** [comment]
Hello @mojtabakarimi 

I don't know Swiper and how it works. So I'm currently not able to help you, as it is impossible for me to know all plugins/libraries out there. I'm sorry.
