### ISSUE TITLE
Documentation method casing

### ISSUE THREAD

**Issue by inspector71** [eisbehr-/jquery.lazy#155]
There are some pages of the documentation that have a capital L when calling the method name. That is:

"`.Lazy()`"

where some other pages have:

"`.lazy()`"

Perhaps this could be made more consistent. 

Is this is documentation I can edit somehow via git I'd be happy to help.

**Comment by eisbehr-** [comment]
Hello @inspector71 

that's because Lazy is is not case-sensitive. Both is possible, nothing is wrong. ;)
But thanks for your feedback.
