### ISSUE TITLE
Images and data-src don't loaded in Safari

### ISSUE THREAD

**Issue by spiritius** [eisbehr-/jquery.lazy#156]
Hi.

MacOs and iOS Safari have a really strange loading of images and background-images.
Examples: 
https://www.yuga.ru/photo/4353.html photo grid as `<a data-src="" class="lazy">` (`<a>` with images as background) is loading properly only after page reload.
https://e.yuga.ru/photo/6.html photo grid as `<img data-src="" class="lazy">` (just images) isn't loading at all.

Screenshots: (network panel, images hadn't even requested): 
https://spiritius.net/temp/git/lazy1.jpg
https://spiritius.net/temp/git/lazy2.png

Chrome/FF is ok.

Thanks.

**Comment by eisbehr-** [comment]
Hello @spiritius 

If I open the page with Safari, I get the following error in console:

> TypeError: $('.sticky').Stickyfill is not a function. (In '$('.sticky').Stickyfill()', '$('.sticky').Stickyfill' is undefined)

So, is it possible, that your issue doesn't belong to Lazy? If I open the page with other browsers, I don't get this error. So you seem to have some other problems there ...

**Comment by eisbehr-** [comment]
This link works fine in safari?!

**Comment by spiritius** [comment]
No, it doesn't

**Comment by eisbehr-** [comment]
Even if you say no, for me it does. ;) Everything load fine, as expected. With a little fade in too.
Do you got any errors?

**Comment by eisbehr-** [comment]
Actually now, all pages are working in Safari now. Do you changed anything?! It's all good actually here.

**Comment by spiritius** [comment]
iOS: https://spiritius.net/temp/git/lazy3.jpg
also, https://www.yuga.ru/photo/4353.html is this link works for you?

I didn't change anything.

**Comment by eisbehr-** [comment]
All links are working now! It's just fine.

But I have an idea. By default Lazy will start working after `window.load` event. But I noticed that some resources of this pages acts slow, what would Lazy to delay. Maybe try to initialize Lazy instantly.

You can do this with the `bind` config parameter:

```JS
$('.lazy.).Lazy({
    bind: 'event'
});
```

Maybe give it a try ...

**Comment by spiritius** [comment]
We have it already:
`var lazy_params = {
			visibleOnly : true,
			effect      : "fadeIn",
			effectTime  : 500,
			threshold   : 200,
			bind        : 'event'
		};`

https://www.yuga.ru/photo/ you can try another materials. for me they start working only after page reload.
and iOS Safari starts working  after several reloads (but sometimes it works normally) :-\

another example: 
https://www.yuga.ru/photo/4332.html
![lazy4](https://user-images.githubusercontent.com/7029587/42171216-65a67f9a-7e21-11e8-8658-6b9ff93c21e3.jpg)

**Comment by eisbehr-** [comment]
Ohh, could you set `visibleOnly` to `false` for a test? We had problems on iOS in past with this parameter. It belongs to the `:visible` pseudo class of jQuery what have issues. Maybe this helps. As far as I see this parameter will have no impact on your page too. So maybe just remove it ...

**Comment by spiritius** [comment]
Had changed to 'false'. No effect.
iOS safari - https://www.yuga.ru/photo/4249.html for example
![lazy5](https://user-images.githubusercontent.com/7029587/42206416-b2bd64e0-7eaf-11e8-865c-dc4424d50429.jpg)

**Comment by eisbehr-** [comment]
Okay, I noticed the following behavior now:

- If I load a page the first time, I always get the following error in console and the images are not loaded:
  > TypeError: $('.sticky').Stickyfill is not a function. (In '$('.sticky').Stickyfill()', '$('.sticky').Stickyfill' is undefined)

- If I refresh the page the error disappears and all images are loaded correctly.

- If I flush my browser cache for the site, the error comes back and the images don't work again until refresh.

So actually I'm pretty sure, you have another problem in your page! As I said earlier, you need to fix the issue with your `stickyfill` script. I think you have a wrong load order somewhere. You seems to use the `stickyfill` plugin before the file was loaded. This issue resolves every time the page is cached.

So please fix this issue first, before we try to resolve your issue with lazy! ;)

**Comment by spiritius** [comment]
![lazy6](https://user-images.githubusercontent.com/7029587/42213611-f11c62d8-7ec1-11e8-99a0-a7f09115b825.jpg)
There are no any errors as well as images. :)

**Comment by eisbehr-** [comment]
The error is still there, on the exact same page you have open in your browser. Are you sure you have flushed your cache?

<img width="910" alt="error" src="https://user-images.githubusercontent.com/917005/42217580-0860d57e-7ec6-11e8-88e1-7d85ab684ae2.png">

**Comment by spiritius** [comment]
Well, you are right. stickeyfill() and cash are actually the causes of my problem.
Thanks you sooo much! (just opened my eyes)
