### ISSUE TITLE
Getting the W/H of the loaded image

### ISSUE THREAD

**Issue by can92** [eisbehr-/jquery.lazy#159]
Hello,

is it possible to retrieve the real image width & height of the loaded image?
I'am building a dynamic image Loader. The div in which the image is loaded is smaller than the original image tho.

Atm this is my code to retrieve the width and height:
```javascript
jQuery('.lazy').Lazy({
        scrollDirection: 'vertical',
        effect: 'fadeIn',
        visibleOnly: true,
        afterLoad: function(element) {
            var x = new Image();
            x.src = element.css("background-image").match(/url\("?(.*)"\)/)[1];
            x.onload=function(){
                //WIDTH & HEIGHT AVAILABLE
                console.log(this.width);
                console.log(this.height);
            };
        }
});
```

I want to avoid loading the image again for just getting the width & height tho.
Do you plan on adding variables for this?

Great plug-in by the way!

Cheers!

**Comment by eisbehr-** [comment]
In general, you can use the `element` parameter to get the dimensions. But only if you don't overwrite it with custom settings by css. Then there is no way to get the real dimensions. But this is not an issue of the plugin, it's a general issue with js. 

More information:
https://stackoverflow.com/questions/1944280/determine-original-size-of-image-cross-browser

```JS
element.width();
element.height();
```
