### ISSUE TITLE
Show images when printing page

### ISSUE THREAD

**Issue by julescakecrumb** [eisbehr-/jquery.lazy#161]
Hi there,

the code works fine, I appreciate your work but here's my question:
When I want to print the page (without having scrolled to each image first), the images aren't visible in the browser print-preview. I assume they won't be printed as a result, too.
Is there any possibility to correct this with the settings of jQuery Lazy?
Any other, smart approach to this issue would be great, too. 🙌🏻

_I am not very experienced in JS/jQuery so maybe this question might seem redundant or the solution is super-easy.
I am thankful for any help!_

**Comment by eisbehr-** [comment]
You can call the `force` function on all images before you print the page. That would cause the instant loading of all images. Hope this helps.
