### ISSUE TITLE
visibleOnly issue with Chrome

### ISSUE THREAD

**Issue by vkanev** [eisbehr-/jquery.lazy#162]
Hello,

I am using this script to handle images lazily. As there are pages with lots of images and don't want to generate excessive bandwidth I use "visibleOnly: True". It's working as expected when there are visible and not visible images.

On Chrome browser there is a problem when all images are visible (in viewport). The problem is that the images are not loaded when "visibleOnly" option is set to True. But when we have not visible images, everything works fine. I have set this option to False, just to test if this will solve the loading problem and it does solve it. After changing it, I have tested a page with many images. Now all images are loaded, regardless if they are visible or not, which is expected. Meanwhile when testing with Firefox, only visible images are loaded even "visibleOnly" option is set to False.

Here is the JS code I am using (Here the option is commented, because I use the default value (False), but I want to set it to True.):
`
	$('img.lazy').Lazy({
/*		visibleOnly: true,*/
		effect: 'fadeIn',
		effectTime: 500,
		threshold: 100,
	});
`

Here is the HTML code of an image:
`<img itemprop="image" class="img img-responsive lazy" content="***/19165/image" alt="***" src="***19165/image/500x500">`

I am using v.1.7.7 at the moment.

**Comment by eisbehr-** [comment]
Well, yes. There are issues with the `visibleOnly` option. For example, Safari hat problems too. But that is nothing I can improve or fix. For the visibility check Lazy only uses jQuery's own function, like: `element.is(':visible')`. The issue belongs to this pseudo class. I'm sorry, but my best hint at the moment is, to don't use the `visibileOnly` option.
