### ISSUE TITLE
Extra File for Youtube with no cookie when using iframe

### ISSUE THREAD

**Issue by MacKP** [eisbehr-/jquery.lazy#165]
It would be great if there would be an jquery.lazy.youtube-nocookie.js for this url:
`https://www.youtube-nocookie.com/embed/`

I would prefer an extra file for choosing what you want ;-)

regards

**Comment by MacKP** [comment]
I made this changes in new files -> #166

**Comment by eisbehr-** [comment]
Nice idea, I will quickly implement this in the original plugin, because this is just a setting and a nice extension for it. Thank you for the hint! I will notice you here ...

**Comment by MacKP** [comment]
Thx a lot! :)

**Comment by eisbehr-** [comment]
I have added this option to the loader. Simply set it as attribute:

```HTML
<iframe data-loader="youtube" data-src="1AYGnw6MwFM" data-nocookie="1" width="560" height="315" frameborder="0"></iframe>
```

Thank you for your feedback!
