### ISSUE TITLE
lazy not working with slick slider.

### ISSUE THREAD

**Issue by hsharma89** [eisbehr-/jquery.lazy#168]
Hi,
 I am using sliders in my project. There are multiple slick sliders on my page. Lets say around 50. Now each slider has 10-20 images. When i scroll down lazy loading is working fine. But when i scroll horizontal on slick slider images are loading. 
Can you give some workaround.

Thanks

**Comment by eisbehr-** [comment]
Questions about sliders have been answered so many times. Please look at other issues.
