### ISSUE TITLE
Hidden images loading

### ISSUE THREAD

**Issue by trikon** [eisbehr-/jquery.lazy#169]
Tell me please, how can i fix issue when images are in `display:none` block(mobile version) and why they are loaded anyway even if they are not visible in view port(they are far below in footer)?
Thanks!

**Comment by eisbehr-** [comment]
This could have multiple reasons. But how could I tell you?! I have no idea what you did.

**Comment by schuppeste** [comment]
Hi, same Problem. Trikon,Found Solution?
