### ISSUE TITLE
Slower reload of pages with lazy load enabled?

### ISSUE THREAD

**Issue by fmahannah** [eisbehr-/jquery.lazy#170]
We are optimizing many real estate listing pages for better google mobile speed ranking and using lazy load to help with this. When google test times page loads it seems to use the reload time and not initial page load time. So on a page where we were loading 25 listing images google was returning a time of 9s. With lazy load we only load around 5 or 6 of these images and google returns a time of 10s. Testing with webpagetest.org showed that initial page load time improved from 18.6 seconds on 3G to 16.1 seconds with lazy loading, BUT the reload time went from 6.1 seconds up to 9.5 seconds for that same page?

Does anyone know what would cause a page reload to be slower with lazy loading than an initial page load? Meaning when caching should improve load speed it it actually making it slower than it was without lazy load enabled. We are using a CDN for the listing images that we are lazy loading.

Here is an example page if you want to do any tests of your own on mobile. Lazy load is enabled:

https://www.terravistarealty.com/real-estate-NC-davidson.cfm

Any tips or advice appreciated because we thought lazy loading would improve page load speed on google test because it loads 20 less images, but in reality we are losing 1-2 seconds compared to load times without lazy loading. if we can't resolve this we will have to turn off lazy loading to get the reload times back to what they were without it

Thanks!

**Comment by eisbehr-** [comment]
Hello @fmahannah 

This is interesting. I've never heard about such thing. Not in relation with Lazy nor any other library. You can measure the page loading speed by yourself, with your browser. I clearly see faster loading times, not slower. The only thing I could think about at the moment, is that the google site parser interprets the fact of delayed loading wrong. I don't know why and I actually don't have an answer, whats wrong on your site. 

It would be create if there is an time diagram, where we could see what parts of the loading are slower on refresh. Without it's hard to investigate such problems. Maybe it's the cdn too?!

I leave this open for now ...

**Comment by fmahannah** [comment]
It looks like what happens on reload is that the images that lazy load on initial display are loading after the dom loads and that somehow slows down a reload. On a typical page 4 or 5 images have to load when the page first displays. IF I set those first 4 or 5 images to not use lazy loading then the slow reload times go back to normal. So for whatever reason on a page reload when caching should improve load times the lazy load makes them slower. I agree that it makes no sense.  I will see if I can share with you waterfall charts showing an example.
