### ISSUE TITLE
Lazy images load on pageload

### ISSUE THREAD

**Issue by mikeboothdesign** [eisbehr-/jquery.lazy#171]
I am having an issue with this plugin. It seems to load images at the bottom of my page about 1000 pixels below the screen as soon as the page loads

`<img class="srcSet" data-src="123.jpg" data-srcset="123.jpg 480w, 456.jpg 768w" />`

```
$('.srcSet').Lazy({
      afterLoad: function(element) {
          // after an element was successfully loaded, 
          console.log('loaded');
      },
});
```

Here I can see that the console.log happens immediately on page load ands also the image src is loaded on page load even though those images are very far below the bottom of my screen.

Am I doing this incorrectly?

**Comment by mikeboothdesign** [comment]
For anyone who might stumble across this question: I figured it out.

The images were set to display: none via CSS. I guess this means they were not displayed in the flow of the document and for some reason were loaded instantly.

What I'm actually doing is lazy-loading responsive background images. So lazy-loading the images at the correct size with srcset, and then on the afterload callback, deleting the image and setting the currentsrc as the background image. Super fast page!

**Comment by omarojo** [comment]
Hi there mate.. Im also having the same issue.
all my images get loaded/request as soon as I finish retrieving the json file that has all the urls. 
What I do is
1- Request a json file with image urls
2- jquery append <img> elements to the page
3- call the lazy() method.

still.. all images get loaded.
here is my site: https://g8civilized.herokuapp.com/mosaic?showall=true
You can see the source code right there. 

but this is the important part.You can see in the console how it loads all of them no matter what.

```
function creategGrid(data) {
                imagesArray = data;
                imagesArray.forEach(function (element) {
                    if (element.document) {
                        var imgUrl = element.document.fields.imageUrl.stringValue;
                        var artImgCol = $("<div>", { 'class': 'col-6 col-sm-3 col-md-2 col-lg-2 col-xl-1 mb-3 px-2 mx-0 text-center' });
                        var artImg = $('<img>', { 'class': 'lazy mosaic-image' })
                        artImg.attr("data-src", imgUrl)
                        artImgCol.append(artImg);
                        $('#mosaicPage').append(artImgCol);
                    }
                });
                $(function () {
                    $('.lazy').Lazy({
                        visibleOnly: true,
                        effect: "fadeIn",
                        effectTime: 2000,
                        bind: "event",
                        afterLoad: function (element) {
                            console.log("Image Loaded", element)
                        }
                    });
                });}
```
