### ISSUE TITLE
custom data-loader causes "Uncaught TypeError: Cannot read property 'indexOf' of undefined"

### ISSUE THREAD

**Issue by hightechguy** [eisbehr-/jquery.lazy#173]
Taking from the description:

```
    $(function () {
        $('.lazy').lazy({
            // custom loaders
            customLoaderName: function (element) {
                element.html("element handled by custom loader");
                element.load();
            },
        });
    });
```

on
`<div class="lazy" data-loader="customLoaderName"></div>`
causes error
Uncaught TypeError: Cannot read property 'indexOf' of undefined
in console
with https://code.jquery.com/jquery-3.3.1.min.js

Switching to http://code.jquery.com/jquery-latest.js fixes the issue

**Comment by eisbehr-** [comment]
I can't recreate that issue. Please provide more information if the problem remains.
https://jsfiddle.net/zdLnk0mb/1/

Another hint, if you use elements like `div`, better use the `respond` function instead of `.load()`:
https://jsfiddle.net/zdLnk0mb/2/
