### ISSUE TITLE
Lazyload image follow media width?

### ISSUE THREAD

**Issue by Keither** [eisbehr-/jquery.lazy#179]
Hi,
if i want to lazyload image follow media width

1. media(min-width: 300px): load image a.jpg
2. media(min-width: 600px): load image b.jpg
3. media(min-width: 900px): load image c.jpg

I saw this link http://jquery.eisbehr.de/lazy/example_use-srcset-and-sizes
but i dont understand
can help me pls

Thanks so much!
Sorry my English not good!

**Comment by eisbehr-** [comment]
Hello @Keither 

There are many, many tutorials on the web about `srcset` and `sizes`. I think you will find something that will help you and match your needs. It's a bacis html functionality and nothing special about Lazy.

For example:
- https://bitsofco.de/the-srcset-and-sizes-attributes/
- https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
