### ISSUE TITLE
Does it support .webp format?

### ISSUE THREAD

**Issue by weilinzung** [eisbehr-/jquery.lazy#183]
Does it support .webp format?

When I use it, that change to the Base64 image as an src.

`<img class="img-fluid lazy" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==" data-src="/img/van.webp" alt="Van">`

**Comment by eisbehr-** [comment]
Lazy supports every image format your browser supports.


The base64 image is a palceholder Lazy sets for you, to prevent broken images shown in browsers. That will be replaced after load. You can change that behavior in the settings. If you don't want this, set `defaultImage` to an empty string,

https://github.com/eisbehr-/jquery.lazy#configuration-parameters

**Comment by weilinzung** [comment]
got it. thanks for explaining that.
