### ISSUE TITLE
The image is not displayed.

### ISSUE THREAD

**Issue by Flareonn** [eisbehr-/jquery.lazy#184]
Slider created. The site is hosted on CMS WordPress. To display the files used php code. Below I placed the code. Instead of the image on my website is just a white background.

On another site the plugin works correctly, copied the code completely from it. I meet with the error described above.

```
<div class="product-slider_for product-slider_for_m">
 <img data-src="<?php echo get_template_directory_uri(); ?>/img/item-1.jpg" src="" class="lazy">
 <img data-src="<?php echo get_template_directory_uri(); ?>/img/item-2.jpg" src="" class="lazy">
 <img data-src="<?php echo get_template_directory_uri(); ?>/img/item-3.jpg" src="" class="lazy">
 <img data-src="<?php echo get_template_directory_uri(); ?>/img/item-1.jpg" src="" class="lazy">
 <img data-src="<?php echo get_template_directory_uri(); ?>/img/item-2.jpg" src="" class="lazy">
 <img data-src="<?php echo get_template_directory_uri(); ?>/img/item-3.jpg" src="" class="lazy">
</div>
```

**Comment by Flareonn** [comment]
functions.php: 
`				<?php 
	add_action( 'wp_enqueue_scripts', 'theme_name_scripts' );
	function theme_name_scripts() {
		wp_enqueue_style( 'style', get_stylesheet_uri() );
		wp_enqueue_style( 'bootstrap', get_template_directory_uri() . '/css/bootstrap-grid.min.css' );
		wp_enqueue_style( 'animate', get_template_directory_uri() . '/css/animate.css' );
		wp_enqueue_style( 'slick', get_template_directory_uri() . '/slick/slick.css' );
		wp_enqueue_style( 'slick-theme', get_template_directory_uri() . '/slick/slick-theme.css' );
		wp_enqueue_style( 'main', get_template_directory_uri() . '/css/style.css' );
  wp_deregister_script( 'jquery' );
  wp_register_script( 'jquery', 'https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js');
  wp_enqueue_script( 'jquery' );
		wp_enqueue_script( 'main', get_template_directory_uri() . '/main.js', array('jquery'), null,true);
		wp_enqueue_script( 'slick', get_template_directory_uri() . '/slick/slick.min.js', array('jquery'), null,true);
		wp_enqueue_script( 'wow', get_template_directory_uri() . '/js/wow.min.js', array('jquery'), null,true);
		wp_enqueue_script( 'lazy', '//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.10/jquery.lazy.min.js', array('jquery'), null,true);
	};`

main.js:
 `				$(function($) {
			  $("img.lazy").lazy({
			      effect: "fadeIn",
			      effectTime: 2000,
			      threshold: 0
			    });
				});`

**Comment by eisbehr-** [comment]
Questions about sliders/carousels have been answered so many times. Please look at other issues.
