### ISSUE TITLE
lazy load for Horizontal Scroll without fixed width

### ISSUE THREAD

**Issue by hendrikleper** [eisbehr-/jquery.lazy#187]
Hi,
Is there a solution to implement jquery.lazy for a horizontal scroll with images that have irregular dimensions (width and height)?  

Thanks,
Hendrik

**Comment by eisbehr-** [comment]
Yes, if they have a `width` an `height` it doesn't matter if they are different. And horizontal scroll is supported too.

**Comment by hendrikleper** [comment]
👍 Thanks.
