### ISSUE TITLE
Element data-src not allowed as child of element picture in this context. (Suppressing further errors from this subtree.)

### ISSUE THREAD

**Issue by Aleksandr2015** [eisbehr-/jquery.lazy#188]
hi, eisbehr. I have been using your wonderful plugin in each of my projects for several years, during use it showed itself very well and honestly speaking at certain moments looked at other options for lazy loading images, but i was returned to yours plugin because I did not find anything better in functionality from the box. 

Now to the point: it has recently become necessary to use a plugin in the project to work with the ```<picture>``` tag. Everything is fine, the plugin works like a clock, but there is a problem, it may seem insignificant and "not affecting performance", but it is https://validator.w3.org 

It show errors:
```
Element data-src not allowed as child of element picture in this context. (Suppressing further errors from this subtree.)

Element data-img not allowed as child of element picture in this context. (Suppressing further errors from this subtree.)

Element picture is missing a required instance of child element img.

``` 
This is understandable, because inside the tag we put elements that are not described in the specification.

Quick solution of this problem may be to use html markap not as like ``` <picture>``` tag, but a simple ```<div>``` tag with its subsequent replacement to ```<picture>``` tag, similar as ```<data-srcset>``` and ```<data-img>```.

What do you think about this problem and proposed solution?

Thank you for your attention to my question.

**Comment by eisbehr-** [comment]
Yes, the html is not valid by w3c, but this is not affecting anything. It will work in every browser. If you want to suppress this, you could rewrite your image tags to a [singe line markup](https://github.com/eisbehr-/jquery.lazy/tree/master/plugins#picture-loader) (not working with all picture tags) or simply build a c[ustom loader](https://github.com/eisbehr-/jquery.lazy#custom-content-loaders) on your own, if you want to use something like a div container. It should be pretty easy.
