### ISSUE TITLE
Horitzontal Loading only loading after Vertical Scrolling

### ISSUE THREAD

**Issue by whittyskitty** [eisbehr-/jquery.lazy#189]
Hello, 

I have images that are within li that are displayed horitzontally and when they enter the viewport, the images do not load until I scroll down 1 pixel and that initiates the hortizontal loading.

I was wondering if it does not load because my images are within a li?

Here is my CSS:

`li.products {
display: inline-block;
}
ul.products {
    overflow: auto;
}

html:
`<li class="product"><div class="entry-product"><div class="entry-featured"><a class="linkClass" href="https://dev.whitakerhouse.com/shop/product/breaking-emotional-barriers-to-healing/"><img class="attachment_thumbnail" data-src="/path/to/image"> </a></div></div></li>`

**Comment by pichaya-om** [comment]
I have the same problem :(

**Comment by whittyskitty** [comment]
Hey Pichaya,

I was actually able to get it to work by using his elements within a container: http://jquery.eisbehr.de/lazy/example_elements-inside-a-container

Just specify the list or div's class and replace his: #lazy-container with your class. Then specify the class of the images you would like to lazy load. In his example, it is .lazy 

Hope this helps!

**Comment by ttmthanh** [comment]
How about it? :'(
