### ISSUE TITLE
Images are loaded twice in Safari on desktop

### ISSUE THREAD

**Issue by andersnoren** [eisbehr-/jquery.lazy#192]
MacOS 10.14.2
Safari 12.0.2
No browser plugins active

Steps to reproduce:
Visit the [Basic usage demo](http://jquery.eisbehr.de/lazy/example_basic-usage) in Safari, open the resources tab in the developer tools and scroll down the page. Each image is loaded twice.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/8181091/51072426-d358e280-1660-11e9-896f-c9571a60793e.png">

**Comment by stephenhmarsh** [comment]
Fwiw, I'm on the exact same macOS and exact same Safari on a 13.3-inch (2560 x 1600) retina display, and I am not able to reproduce this.

**Comment by stephenhmarsh** [comment]
At what time(s) do you see the images get requested and loaded in the Network tab?

**Comment by andersnoren** [comment]
Both are loaded at about the same time when I reach them on the page. Screenshot: 
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/8181091/51100499-ab8b8b00-17d6-11e9-9786-66e6f9897e1d.png">

**Comment by eisbehr-** [comment]
This happens just because Safari will disable the browser caching, when you have the network tab of the developer tools opened. Do you see the small blue icon in the upper right of you last screenshot? Just disable this options and try again. Everything should work as expected then. ;)

**Comment by q2apro** [comment]
In Chrome it's "Disable Cache" top right:

![image](https://user-images.githubusercontent.com/6764548/77318033-faa34900-6d14-11ea-81b6-d4d8f0312ad8.png)
