### ISSUE TITLE
Lazy Loading not working on iPhone and iPad

### ISSUE THREAD

**Issue by oscarhandsome** [eisbehr-/jquery.lazy#194]
I have a live site [http://almall.com](http://almall.com)
I Implemented lazy loading a few weeks ago, and it was fine, but now my script not working. This issue only on iPhone and iPad devices.
Does somebody have this issue?

**Comment by eisbehr-** [comment]
Are there any errors you might get in console or something? Maybe something has changes. It's hard to say what could causes your issues. And what is you Lazy config?

**Comment by eisbehr-** [comment]
Thank you both for you reports. I actually got no iPhone to my hands for a test. A question, are the initial images loading when you load the page or are they missing too?

**Comment by oscarhandsome** [comment]
> Are there any errors you might get in console or something? Maybe something has changes. It's hard to say what could causes your issues. And what is you Lazy config?

Hello
1) Thank you for lazy loading
2) code:
`$(function($) {
                $("img.lazy").Lazy();
            });
`
3) no one issue in console
4) don't know how trace it on iPhone
5) i resolved this issue by adding to each block to each category jquery code and lazy loading func, not only in the footer, my optimization goes out lol, but will review soon this issue and might will be remove a lazy ;(

**Comment by eisbehr-** [comment]
Thank you @oscarhandsome 
I would like to try to solve this issue, so that everything will work again as expected.

One thing i saw in your page now is the following:

```JS
window.addEventListener('load', function () {
    $(function($) {
        $("img.lazy").Lazy();
    });
});
```

You use a jQuery ready state inside of a `window.load` event listener. This could cause a problem, that the inner of the ready state will not executed, because jQuery can not determine anymore if it's already loaded or not.

This could even be the reason why you have problems on some devices. So at first, try to remove the ready state:

```JS
window.addEventListener('load', function () {
    $("img.lazy").Lazy();
});
```

**Comment by oscarhandsome** [comment]
Yeah but, i need revert all scripts to async working, before was without nothing.....

**Comment by eisbehr-** [comment]
I don't understand you last comment?!

**Comment by oscarhandsome** [comment]
i mean i'm optimizing all scripts for google page speed.

**Comment by eisbehr-** [comment]
And what has that in common with removing the jQuery ready state like i suggested?

**Comment by oscarhandsome** [comment]
Without `window.load` i can't detect new blocks when page is loaded

**Comment by eisbehr-** [comment]
Please read my post again. I never said you should remove the `window.load` part! You should remove the `$(function($) { });`

**Comment by oscarhandsome** [comment]
> Please read my post again. I never said you should remove the `window.load` part! You should remove the `$(function($) { });`

ah, okay, i will try to check, and will answer here about results

**Comment by oscarhandsome** [comment]
> Thank you both for you reports. I actually got no iPhone to my hands for a test. A question, are the initial images loading when you load the page or are they missing too?

i has a iPhone and iPad, we can test is you want anything

**Comment by eisbehr-** [comment]
Do you have any results @oscarhandsome ?

**Comment by oscarhandsome** [comment]
> Do you have any results @oscarhandsome ?

Will answer soon.

**Comment by oscarhandsome** [comment]
issue not in the Lazy loading, issue that component on the main page block with a category pic loading in php from another tpl, i have on the main page all scripts what i need, but Jquery don't see elements from other components, this is an issue.

**Comment by eisbehr-** [comment]
Sounds like you have some design issues in your project then. ;) Good luck by fixing them. I would close the issue then, because you already said Lazy is not the issue. Feel free to get in contact of you might have an issue with Lazy in the future.

**Comment by oscarhandsome** [comment]
> Sounds like you have some design issues in your project then. ;) Good luck by fixing them. I would close the issue then because you already said Lazy is not the issue. Feel free to get in contact of you might have an issue with Lazy in the future.

Thanks
This is not a design issue. The issue about when you apply another component from another and using async loading. This is an architecture issue of JS. Anyway, thank you for fast answers.
