### ISSUE TITLE
TypeError: q is undefined - Webpack and jQuery.Lazy();

### ISSUE THREAD

**Issue by Sordum** [eisbehr-/jquery.lazy#195]
Hey,

I've got a problem with including into webpack.
I installed it and I alway get the error "TypeError: q is undefined" in my browser console.

The Plugin is in my bundle.js, but I always get this error.
What can I do to fix that?

Greetings...
Paul

**Comment by eisbehr-** [comment]
Please check your build process and the order of your scripts in your bundle. There seems to be an issue. And the question is, if this error belongs to Lazy or something else in your script too. But if you use original Lazy files there is not such error.
