### ISSUE TITLE
it's very cool but load twice

### ISSUE THREAD

**Issue by tmjqr** [eisbehr-/jquery.lazy#200]
it's very cool but load img twice

**Comment by tmjqr** [comment]
when i look the F12 dev model ,i see the img twice loaded

**Comment by eisbehr-** [comment]
Is your `doctype` set correctly?

**Comment by tmjqr** [comment]
thank you ,   i used like  this
"  $(function() {
        $('.lazy').lazy();
    });  "
and  i see the demo site , F12 -> network   . i found twice load the same img.

**Comment by eisbehr-** [comment]
https://github.com/eisbehr-/jquery.lazy/issues/192

**Comment by tmjqr** [comment]
thank you
