### ISSUE TITLE
Use delay in a better way

### ISSUE THREAD

**Issue by developedsoftware** [eisbehr-/jquery.lazy#202]
I was hoping that delay would 'delay' the loading of visible images x number of seconds. 

So that by scrolling up and down aggresivly that it would wait x seconds before working out what was displayed and then lazy load them. 

If I have a page of 400 images, and scroll to the bottom - there is a delay loading the images because its trying to load the 399 images above it as its scrolled. 

Can it be improved so that the evalution of 'visible' images is done x amount of seconds after scrolling has finished?

**Comment by eisbehr-** [comment]
I think you mean `throttle`, not `delay`.
