### ISSUE TITLE
Issue on iPhone

### ISSUE THREAD

**Issue by claudioandresc** [eisbehr-/jquery.lazy#204]
Hello, I have an issue with iPhones, the images doesnt load.
https://www.alegra.com/argentina/

I use this code:

```JS
$('img.lazy').Lazy({
      // your configuration goes here
      scrollDirection: 'vertical',
      effect: 'fadeIn',
      visibleOnly: true,
      onError: function (element) {
        console.log('error loading ' + element.data('src'));
      }
    });
```

If you can help me I really apreciate.
Thanks, regards.

**Comment by eisbehr-** [comment]
As I saw by now, your page works fine. The images gets loaded.

To get the effect working, you need to set `effectTime` too.
