### ISSUE TITLE
Accodion Loading all images on pageload

### ISSUE THREAD

**Issue by schuppeste** [eisbehr-/jquery.lazy#205]
Hi, 
The Plugin works good,  now i have add a accordion to separates the pictures in Tabs. 

On this change all pictures loads automaticle at pageload in random order. 

Herachy Div classes: .accordion .dogs .lazy
Dogs= multiple div Container with images 

in Deutsch:
Also das Plugin lief super, dann habe ich die DIVs in denen die Bilder sind mit einem Accordion versteckt, jetzt werden die Bilder schon beim Laden der Seite geladen. Die Bilderreihenfolge scheint frei zufällig zu sein.

**Comment by eisbehr-** [comment]
I think the problem is, that an a accordion hides the elements on a small place. So basically, all images are in the viewport on loading. So it would be correct to load them. I think for an accordion you would need a bit other process.
