### ISSUE TITLE
Multiple background images

### ISSUE THREAD

**Issue by rgrasby** [eisbehr-/jquery.lazy#207]
I currently serve my background images in multiple sizes for each viewport (xs, sm, md, lg). Is there anyway to lazyload all background images depending on the device a user is using? Thanks in advanced.

**Comment by eisbehr-** [comment]
There is currently no way by default. But you could easily create a [custom laoder](https://github.com/eisbehr-/jquery.lazy#custom-content-loaders) for this task.
