### ISSUE TITLE
Images Load Twice

### ISSUE THREAD

**Issue by jgeringer** [eisbehr-/jquery.lazy#208]
This plugin is great, but just noticed that it's loading the images twice. 

To reproduce:
1) http://jquery.eisbehr.de/lazy/example_basic-usage
2) Open network tab
3) Scroll down and notice the same image gets loaded twice

**Comment by dirkill** [comment]
It seems to happen when DevTools - disable Cache.

**Comment by jgeringer** [comment]
Ah, yes you are correct, thanks!

**Comment by Sudharshaun** [comment]
It shouldn't happen right ? Even when disabling cache the browser should be downloading the image once right?

**Comment by eisbehr-** [comment]
It a normal behavior of the developer tools. That's not uncommon and no fault of the plugin. Go and ask Google/Firefox about their tools. ;)
