### ISSUE TITLE
Images in scrolling div in bootstrap modal all load when calling .lazy()

### ISSUE THREAD

**Issue by Bremaweb** [eisbehr-/jquery.lazy#209]
I have images in a modal in a scrolling div. When `$("#lazy-container .lazy").lazy({appendScroll : $("#lazy-container")});` is called, all of the images load. I have a callback for the `shown.bs.modal` event that calls the above line to begin lazy loading the images in the modal and all of the images load immediately.

**Comment by Bremaweb** [comment]
https://jsfiddle.net/BrandonReese/3xc2we7o/13/

**Comment by eisbehr-** [comment]
I think this may happen because there is no default dimension and the way how BS handles the modal. So on loading all images may fit in the current viewport. This may cause this issue here. But to me sure i woudl have to dig in the code. But currently i got not enough time for this.
