### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by niramber** [eisbehr-/jquery.lazy#21]
Hello,
How can I unbind or destroy lazy load from all binded elements?
I am loading images via ajax and binding the event to each image 
 $("img.lazy", "#categoryList").lazy({ bind: "event", effect: "fadeIn", effectTime: 250, delay: -1 });

the problem I have is: each time I click a button to load more images( some images are removed) its not releasing the bind event and the page becomes slower and slower and the memory increases. 

if I don't use lazy load the page does not slow down after each ajax call when scrolling

**Comment by ktusznio** [comment]
+1, I also need a way to disable the plugin after it is initialized.

**Comment by eisbehr-** [comment]
Hey guys,

please take a look at the new [version 0.4.0](https://github.com/eisbehr-/jquery.lazy/releases/tag/0.4.0). There are different ways now to [destroy](http://jquery.eisbehr.de/lazy/index.php?c=destroy) an single instance.

Hope this works for you.
