### ISSUE TITLE
Percentage Display

### ISSUE THREAD

**Issue by Enkirch** [eisbehr-/jquery.lazy#217]
Hi,
is there anyway to show the progress in percentage ? :-) 

Have a nice day/weekend !

**Comment by eisbehr-** [comment]
Not by default, but that should be pretty easy to do. You count your images and use a callback for update your percentage.

```JS
let images = $('img.lazy');
let amount = images.length;

images.Lazy({
  afterLoad: function() {
    let percentage = (100 / amount) * (amount - this.getItems().length);
    $('.percentage').text(Math.round(percentage) + "% loaded");
  }
});
```

[Working example.](https://jsfiddle.net/msLtdfhr/)
