### ISSUE TITLE
How to handle picture > source elements

### ISSUE THREAD

**Issue by Corrodian** [eisbehr-/jquery.lazy#218]
When using lazy load on picture > source element, it adds the image as a background. I wan't to add it as srcset attribute. How can I accomplish that?

**Before:**
`<picture>`
  `<source class="lazy" data-srcset="img.webp" type="image/webp" />`
  `<source class="lazy" data-srcset="img.jpg" type="image/jpeg" />`
  `<img class="lazy" data-src="img.jpg" />`
`</picture>`

**After:**
`<picture>`
`  <source class="lazy" srcset="img.webp" type="image/webp" />`
`  <source class="lazy" srcset="img.jpg" type="image/jpeg" />`
`  <img class="lazy" src="img.jpg" />`
`</picture>`

**Comment by eisbehr-** [comment]
https://github.com/eisbehr-/jquery.lazy/tree/master/plugins#picture-loader
