### ISSUE TITLE
I found an issue when using unveil with isotope

### ISSUE THREAD

**Issue by rotaercz** [eisbehr-/jquery.lazy#22]
Isotope (http://isotope.metafizzy.co/) is a plugin that can move the images around and also hide and show images based on filters and it seems unveil has trouble knowing when an image is on screen when using it. It would be great if you could support it.

**Comment by eisbehr-** [comment]
Hi @rotaercz,

would you create me an example/fiddle to see your usecase of icotope? Otherwise i'm not able to identify a problem there. Thanks!

**Comment by rotaercz** [comment]
I'm sorry, I posted in the wrong place! I couldn't figure out how to delete this post.
