### ISSUE TITLE
Image not loaded on a sort of carousel on horizontal scrolling

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [eisbehr-/jquery.lazy#223]
Hi, I'm using your library to load all the images on [this page](https://new.greenforniture.it/p/giochi-per-parchi-pubblici/agility-dog/piattaforma-a-shaped) but as you can see on the bottom slider of "prodotti simili" when you scroll to the right, the last 2 images don't loads on show, only if after having showed them, you scroll a little bit... idk why this is happening, but I believe is because then you stop scrolling on that section, the images are too far from the showed section (they are staked horizontally and then traslated using traslate3d(pxs)) that the library doesn't show them... does the threshold effects also this? increasing it might help?

**Comment by eisbehr-** [comment]
The question about sliders is already answered very often here. ;) The "problem" is, that Lazy reacts to `scroll` events to update the images, but on a slide there is no such event. So, use the `update()` function of Lazy. You will find more examples in the closed issues.
