### ISSUE TITLE
image reload in chrome 76.0

### ISSUE THREAD

**Issue by amhoho** [eisbehr-/jquery.lazy#225]
**I'm sure DOM not repeat .**

my code:
```js
$('img.lazy').Lazy({appendScroll:'#test'});
```

network:
![01](https://user-images.githubusercontent.com/24509574/77259531-08c57b00-6cbd-11ea-891a-b9eca0341393.png)

**Comment by eisbehr-** [comment]
https://github.com/eisbehr-/jquery.lazy/issues/208
