### ISSUE TITLE
Support webp background

### ISSUE THREAD

**Issue by Dozentz** [eisbehr-/jquery.lazy#231]
There is an implementation for support background image
Example https://codepen.io/imagekit_io/pen/RBXVrW
Рow to implement support webp background.
Here is my example, but because of the script it loads the version with the webp image

`<div id="soglasovanie" class="img_block scale_block_animate lazy"></div>
#soglasovanie.lazy {background-image: none;background-color: #F1F1FA;}#soglasovanie {background-image: url('/img/soglasovanie.jpg');}.no-webp #soglasovanie {background-image: url('/img/soglasovanie.jpg');}.webp #soglasovanie {background-image: url('/img/soglasovanie.webp');}`

**Comment by eisbehr-** [comment]
Could you please clarify your question? I don't understand what you want.
