### ISSUE TITLE
Question about image height 

### ISSUE THREAD

**Issue by Zombayo** [eisbehr-/jquery.lazy#233]
Hi hi,

I'm using the plugin with image that has predefined width and height, so the browser can calculate how much space it'll need and avoid layout shift. But before the full image load it has correct width, but incorrect height (for height the script doesn't use the predefined height but takes the width of the image). This is not a problem for the square images, but when we have images with width/height ratio > 1 is a little awkward because this lead to layout shift when the actual image is completely loaded,

Is there a way to avoid this.

Thank you in advance !

**Comment by eisbehr-** [comment]
That has nothing really to do with Lazy. If a browser doesn't know the size of an element you will always have a flickering while load. As long as you didn't know the dimension you can't prevent this completely. The only thing you can do is to set a `min-height` with css to those elements, so it doesn't flicker that much. But that is basically what you already did. I'm sorry ...
