### ISSUE TITLE
Update not working properly

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [eisbehr-/jquery.lazy#235]
Hi,
I'm currently working on [this website](https://justitalianwine.com/) and as you can see the first slider (the one with just one row of products), is not working properly. Currently my settings are this:
```HTML
<script src="/assets/js/lazy.js"></script>
<script>
    var lazyContentObject = $('.lazy').Lazy({
        scrollDirection: 'vertical',
        effect: 'fadeIn',
        visibleOnly: true,
        chainable: false,
        beforeLoad: function(element) {
            console.log("one new element is loaded");
        },
    });
    lazyContentObject.update()
</script>
<script>
    var product_4 = $('.product-active-lg-4');
    product_4.on('beforeChange', function(event, slick, currentSlide, nextSlide){
        lazyContentObject.update(); console.log('update');
    });
</script>
```
And as you can see the `update` is logged correctly on the console, but the images of the new products are not loaded, and infact there are no other `"one new element is loaded"` logged except the ones that was logged at the beginning 

Am i missing something?

**Comment by eisbehr-** [comment]
You call `update` on the `beforeChange` event. As it called _before_, how should lazy notice any changes to the content?! Of course there will nothing be loaded.

**Comment by AlbertoSinigaglia** [comment]
Thank you, however using `afterChange` nothing has changed

**Comment by eisbehr-** [comment]
Is it possible that the slider alters the off-screen elements somehow after initialization? Could you try adding `lazyContentObject.addItems('.lazy');` after you initialized the slider? Just for a test.

**Comment by AlbertoSinigaglia** [comment]
Added that line at the end of all the scripts in a `document.ready` event, but nothing has changed. If it might help, the source of the image in the slider looks like this: `<img src="https://data.justitalianwine.com/images/wine/00005/00018/front.png" alt="Petresco Toscana IGT Le Cinciole 2015" style="height: 340px; width: auto;" class="lazy">` and in the network tab i can see the image that is been loaded @eisbehr-

**Comment by AlbertoSinigaglia** [comment]
Update: i've added your line inside the `afterChange` listener like here:
```JS
product_4.on('afterChange', function(event, slick, currentSlide, nextSlide){
    lazyContentObject.addItems('.lazy');
    lazyContentObject.update(); console.log('update');
});
```
and it seems to work fine know (don't ask me why, no idea ahah), however i don't know if adding again every time all the elements it's the right way, (or if it's maybe to heavyweight to do)

**Comment by eisbehr-** [comment]
So the problem seems to be, that the slider may do changes to the elements on initialization. So they wouldn't be in the elements list of lazy. I don't know how often the slider will change those elements. Only once, or on every slide. You can try to move the `addItems` just after the slider initialization (without a `document.ready`) and see, if it will work. If not, the slider does something wired to your elements.

**Comment by AlbertoSinigaglia** [comment]
well it's strange because by the looks of things (not my theme), it is [this one](https://kenwheeler.github.io/slick/) which seems pretty famous, but has a very poor "lazy loader" in it... BTW, thank you so much for the support, really appreciated
