### ISSUE TITLE
How to import script with webpack?

### ISSUE THREAD

**Issue by sabat24** [eisbehr-/jquery.lazy#239]
I installed the script by yarn and then just importet it by: 
```
import 'jquery-lazy';
$(function () {
    $('.lazy').Lazy();
});
``` 
Build is made correctly, but after running that script in browser I get `Lazy is not a function`. I guess that it should be imported differently, but how?

**Comment by dkern** [comment]
I think the issue here is that Lazy has no export. So you can't import it. Could be fixed. ;)
