### ISSUE TITLE
Need to add alt attribute.

### ISSUE THREAD

**Issue by palanivelayudam** [eisbehr-/jquery.lazy#240]
Currently i was using the picture tag like [this](https://www.screencast.com/t/W4yjMlkrJ)..
I need to add alt attribute for image tag which was generating inside the picture tag through lazy, 
how to add alt attribute or custom attribute to the image tag.?

**Comment by palanivelayudam** [comment]
And by the way i need to know another thing, If we add the alt tag to the image via script means is that Good for SEO.?
Will crawler reads the image tag and alt attribute.?

**Comment by palanivelayudam** [comment]
Hai, Can any one help me on this issue for me.?

**Comment by ttakanawa** [comment]
Hello @palanivelayudam 

I can answer your first question. Could you try like below?

```html
<picture>
  <data-src srcset="1x.jpg 1x, 2x.jpg 2x, 3x.jpg 3x" media="(min-width: 600px)" type="image/jpeg"></data-src>
  <data-img src="default.jpg" alt="description of the image"></data-img>
</picture>
```

https://github.com/dkern/jquery.lazy/blob/master/plugins/README.md#picture-loader
