### ISSUE TITLE
feature_request(compatibility): cash support

### ISSUE THREAD

**Issue by Kristinita** [eisbehr-/jquery.lazy#241]
### 1. Summary

It would be nice, if jQuery Lazy will support [**cash**](https://kenwheeler.github.io/cash/).

#### 2.1. Common cause

Web performance.

#### 2.2. Details

For web performance it would be nice to have smaller dependency than [**unmaintained**](https://github.com/madrobby/zepto/releases) Zepto or big jQuery. Currently, I use Zepto dependency solely for jQuery Lazy and I don’t want to have a big Zepto dependency just for that.

#### 3.1. Shortly

From [**cash GitHub Readme**](https://github.com/fabiospampinato/cash#cash):

> Cash is an absurdly small jQuery alternative for modern browsers (IE11+) that provides jQuery-style syntax for manipulating the DOM.

#### 3.2. Details

I copied it from [**cash GitHub Readme**](https://github.com/fabiospampinato/cash#comparison):

| Size               | Cash        | Zepto 1.2.0 | jQuery Slim 3.4.1 |
| ------------------ | ----------- | ----------- | ----------------- |
| Unminified         | **36.5 KB** | 58.7 KB     | 227 KB            |
| Minified           | **16 KB**   | 26 KB       | 71 KB             |
| Minified & Gzipped | **6 KB**    | 9.8 KB      | 24.4 KB           |

A **76.6%** gain in size reduction compared to jQuery. If you need a smaller bundle, we support [**partial builds**](https://github.com/fabiospampinato/cash/blob/master/docs/partial_builds.md) too.

| Features                 | Cash                               | Zepto 1.2.0                    | jQuery Slim 3.4.1              |
| ------------------------ | ---------------------------------- | ------------------------------ | ------------------------------ |
| Supports Older Browsers  | ❌                                  | ❌                             | ✔                              |
| Supports Modern Browsers | ✔                                  | ✔                             | ✔                              |
| Actively Maintained      | ✔                                  | ❌                             | ✔                              |
| Namespaced Events        | ✔                                  | ❌                             | ✔                              |
| Typed Codebase           | ✔ (TypeScript)                     | ❌                             | ❌                              |
| TypeScript Types         | ✔ (generated from code)            | ⚠️ (via DefinitelyTyped)       | ⚠️ (via DefinitelyTyped)        |
| Partial Builds           | ✔ (can exclude individual methods) | ⚠️ (can exclude whole modules) | ⚠️ (can exclude whole modules)  |

### 4. Additional links

1. [**Cash documentation**](https://kenwheeler.github.io/cash/#docs)
1. [**Migration from jQuery to cash guide**](https://github.com/fabiospampinato/cash/blob/master/docs/migration_guide.md)

Thanks.

**Comment by Kristinita** [comment]
I'm not sure that closing issues without any changes or arguments is the best practice.

Thanks.

**Comment by dkern** [comment]
No Problem, here is my answer: I will not invest any time into Cash. ;)
