### ISSUE TITLE
Can I use jquery load() to load my images?

### ISSUE THREAD

**Issue by PeterKarsson** [eisbehr-/jquery.lazy#243]
First of all, thanks for a wonderful plugin. I am trying this code but jquery.laze will not be loaded. What am I doing wrong?

`$("#id").load("load_100_images.php", function() { $('.lazy').lazy({ effect: "fadeIn", effectTime: 2000, threshold: 0 }); });`

**Comment by dkern** [comment]
By default lazy wait for `load` of the browser. You use your own event, so I think you just need the `bind` config parameter:

```JS
$("#id").load("load_100_images.php", function() {
    $('.lazy').lazy({ effect: "fadeIn", effectTime: 2000, threshold: 0, bind: 'event' });
});
```

And maybe limit your new Lazy instance to the elements you just have loaded:

```JS
$("#id").load("load_100_images.php", function() {
    $('#id .lazy').lazy({ effect: "fadeIn", effectTime: 2000, threshold: 0, bind: 'event' });
});
```

**Comment by PeterKarsson** [comment]
> By default lazy wait for `load` of the browser. You use your own event, so I think you just need the `bind` config parameter:
> 
> ```js
> $("#id").load("load_100_images.php", function() {
>     $('.lazy').lazy({ effect: "fadeIn", effectTime: 2000, threshold: 0, bind: 'event' });
> });
> ```
> 
> And maybe limit your new Lazy instance to the elements you just have loaded:
> 
> ```js
> $("#id").load("load_100_images.php", function() {
>     $('#id .lazy').lazy({ effect: "fadeIn", effectTime: 2000, threshold: 0, bind: 'event' });
> });
> ```

Thanks a lot. You made my day.
