### ISSUE TITLE
No more images when scrolling down, why?

### ISSUE THREAD

**Issue by PeterKarsson** [eisbehr-/jquery.lazy#244]
`$("#id").load("load_100_images.php", function() {
    $('#id .lazy').lazy({ effect: "fadeIn", effectTime: 2000, threshold: 0, bind: 'event' });
});`

The above example works but gives me only 10 images. When I scroll down no more images apperars. It should be 100. Can someone please tell me why?

UPDATE: I just discovered that if I rezize my window jquery.lazy adds more images. What does that really mean?

**Comment by dkern** [comment]
There is no default reason, why this didn't work. Basically, it should work. But there may be other issues in your code.

**Comment by PeterKarsson** [comment]
I discovered that if I remove my malibu custom scroll it works. But the problem is that I want the custom scroll. I have tried the Example: Elements Inside a Container (appendScroll), but no success. Any suggestions?

**Comment by dkern** [comment]
If you use non-browser scrolling jQuery not Lazy can detect the scroll. You need to work with events then, telling Lazy when to update. But I can't support you on that, I don't know all libraries out there. Good luck!
