### ISSUE TITLE
How do I append images to jquery.lazy?

### ISSUE THREAD

**Issue by PeterKarsson** [eisbehr-/jquery.lazy#245]
I am using lazy like this. It works very nice.

`	$("#id").load("load_100_images.php", function() {
    	$('#id .lazy').lazy({effect: "fadeIn", effectTime: 2000, threshold: 0, container: $("#id")});
	});`

When the user clicks a button I want to append 100 images. How do I do that?

**Comment by dkern** [comment]
Hello. Please take a look at the documentation, there it is described. In your case use `addItems`.
https://github.com/dkern/jquery.lazy#instances-and-public-functions
