### ISSUE TITLE
Images downloading twice in Chrome

### ISSUE THREAD

**Issue by les113** [eisbehr-/jquery.lazy#251]
Lazyloaded images seem to be downloading twice in chrome Version 96.0.4664.110 (Official Build) (64-bit)

Ok in Firefox 93.0 (64-bit)

Tested at http://jquery.eisbehr.de/lazy/example_basic-usage

version //cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.min.js

**Comment by dkern** [comment]
This has been discussed very often:
https://github.com/dkern/jquery.lazy/issues?q=is%3Aissue+is%3Aclosed+twice

**Comment by les113** [comment]
Ah, I see, sorry
