### ISSUE TITLE
images aren't shown if they doesn't come to visibility by scroll

### ISSUE THREAD

**Issue by paolobenve** [eisbehr-/jquery.lazy#254]
Reproduce in chrome:

- open the chrome console f12, in a way that the available browser window has about a 1300x980 pixels size
- load https://fotocuba.qumran2.net/#!/_f-marino_federico_2008_01
- in the console, execute `$(".gps").hide();`: some previously non visible `<img>`'s are shown, but the image isn't show, the placeholder remains there

**Comment by paolobenve** [comment]
actually a work around could be `$(window).scroll();`, but when/how should it be executed?

**Comment by dkern** [comment]
Lazy only listens to scroll event, not DOM changes. So the described behavior is correct. If you do any changes to the content use `scroll()` as you wrote, or use `lazy.update()` public function.
