### ISSUE TITLE
images with srcset load all at once

### ISSUE THREAD

**Issue by rostikrode** [eisbehr-/jquery.lazy#255]
I am using the plugin with srcset, and all of my images load on initial page load, even when not in viewport. Is there a specific setting that I need to enable ?

**Comment by ostapski** [comment]
confirmed - ...functon '**_isInLoadableArea**' does not function correctly

**Comment by dkern** [comment]
That has nothing to do with any function, it's just wrong usage. ;) I just don't comment this issues anymore because there are enough closed issues with this.
