### ISSUE TITLE
Custom Content Loaders broken with jQuery 3.x

### ISSUE THREAD

**Issue by kinless** [eisbehr-/jquery.lazy#257]
It appears that using jQuery 3.x breaks custom content loading within jQuery.lazy. Tested with jQuery 1.x and 2.x to make sure it wasn't user error and it works fine.

Suspecting it's because jQuery removed portions of their deprecated `load()` method in 3.x. When attempting the `element.load()` inside the customLoaderName function, it throws this error:

![jquery-lazy-error](https://user-images.githubusercontent.com/5661056/181314624-8c292aff-3665-4724-9c85-f0d641c311d6.png)

Researching this error says it's due to using `.load()` instead of `.on("load")`, but I'm not versed enough with javascript to dig into the code and figure out where and how to change this in order to work and remain backward compatible.

**Comment by dkern** [comment]
But then it's an issue of your content loader and not of lazy?! The error message says the error is inside of `blogloader` what is clearly not a lazy function ...

**Comment by kinless** [comment]
@dkern it's simply the name of the custom loader being used. Whether it's `customLoaderName` or `blogloader` is irrelevant since they can be named anything according to your documentation. The full code:

```
<div class="blogarchive" data-loader="blogloader">
[content]
</div>
```
```
$(window).on("load", function() {
		    
	$(".blogarchive").Lazy({
		blogloader: function(element) {
                    element.load();
                }
	});
			
});
```

Like I said, this works just fine with jQuery 1.x and 2.x, but because of the removal of `.load()` in jQuery 3.x it breaks. We just need an alternative to `element.load()` but I'm not sure how that would work with your plug-in (that's the part I'm not really versed in).

**Comment by dkern** [comment]
As you may saw in the docs, you can also use the response callback on any custom loader.

```js
$(".blogarchive").Lazy({
    blogloader: function(element, response) {
        response(true);
    }
});
```

**Comment by kinless** [comment]
@dkern ah ok thank you, that works. I saw the response function but looked like it was only for async situations (which I wasn't using). May want to place a courtesy note in your documentation that the response callback must be used with jQuery 3.x instead of `element.load()`.

Appreciate it!
