### ISSUE TITLE
Doesn't trigger when new elements are toggled in

### ISSUE THREAD

**Issue by simonferndriger** [eisbehr-/jquery.lazy#258]
I use jQuery `.toggle()` to hide/show elements. When an element was initially hidden and therefore was not loaded, the image does not get loaded automatically when it becomes visible. The plugin only reacts on scroll, but not on DOM changes.

It would be nice if the plugin would listen to an event trigger that would force it to recheck which elements are visible.

Currently, I have to iterate through every item and update it manually like so, even with a try catch because sometimes it throws an error:
     `$('.lazy').each(function(){
          try { $(this).data('plugin_lazy').update(); }catch(e){}
     });`

**Comment by dkern** [comment]
Why do you even use lazy loaded for items your are toggling? Build yourself a toggle function what loads the images directly? No need for Lazy. But if you want to use toggle, why not use Lazy in the toggle callback?! Something like this:

```js
$('something').toggle(250, function() {
    lazyInstance.force([$(this)]);
});
```

Otherwise register yourself an event to force an update of Lazy. You can do everything with Lazy.

**Comment by simonferndriger** [comment]
OK, thanks. Let me perhaps rephrase my question: what is the best way to use **jquery.lazy** when I have a fix container which is empty at the beginning, and the content within the container changes regularly? And if a new item is added, it could either be visible or hidden and change visibility depending on filters selected.

When I only create one instance on the container, it doesn't do anything when I update this instance, because the new items are not in it yet I guess. I also use a conditioned `.toggle(display)`, so there is also no callback there.
