### ISSUE TITLE
Don`t change src when exists

### ISSUE THREAD

**Issue by applibs** [eisbehr-/jquery.lazy#267]
How to ensure that Lazy does not change src if it already has a value?

**Comment by dkern** [comment]
The question is, why there are elements with a source, that should not ne changed in a Lazy instance? Don't add them of they should not be handled. And of you change the elements outside of Lazy, then you need to manually remove them from the instance.

**Comment by applibs** [comment]
I have another script that puts in another image from another source before Lazy and Lazy doesn't know about it.
Ideally Lazy would create a data-status attribute after inserting the image into src, saying that src has already been changed. At the same time, if I create such an attribute before Lazy, Lazy will skip that element.
And I can do it with callback like this:
```
afterLoad: function (element) {
    element.attr('data-status', 'done');
}
```

but Lazy dont know what it means, because callback beforeLoad dont know cancel loading. Am I right?
I tested some flow how to do it, but first call is made by beforeLoad, then my outside script made some changes and then afterLoad. I am unable to control Lazy.

**Comment by dkern** [comment]
Three ways:

- Create a custom loader for Lazy.
- Let the other script remove the item from that Lazy instance to Lazy doesn't handle that item at all.
- But the best idea would be to create a clean behavior. Two script changing the same attribute on one item is never a good idea. I would suggest changing the workflow.

**Comment by applibs** [comment]
I see that handledName dooing what I am looking for.
