### ISSUE TITLE
allow adding additional items to be lazy loaded

### ISSUE THREAD

**Issue by zspitzer** [eisbehr-/jquery.lazy#27]
Would it be possible to add a new function to allow adding additional items to be lazy loaded,
I'd like to avoid multiple lazy plugin instances running for different content blocks when context is being dynamically loaded / generated?

It would probably need an autoDestroy: false option

**Comment by zspitzer** [comment]
I have a working patch, also including support for loading non image content which I'll post next week

**Comment by eisbehr-** [comment]
Thanks for your help! I'll comment here again once I've got time to review the features.

**Comment by eisbehr-** [comment]
Hello @zspitzer,

I've reviewed the code and pushed a new version to feature branch. Maybe you like to take a look and give some feedback. I'll keept all your ideas in there, but made some changed to behavior, syntax and names.

I noticed your `show()` function and description. But I've found no problems with the `update()` function at all. Can you create a fiddle or test-case where I'll could investigate on this?

Thanks!

# Examples / new Syntax

### Add Items
```JS
var lazy = $("img.lazy").lazy({chainable: false, autoDestroy: false});
lazy.addItems($("img.more")).update();
```

### Custom Loader
```HTML
<div class="lazy" data-loader="customLoader">not loaded</div>
<div class="lazy" data-loader="anotherLoader">not loaded</div>
```
```JS
$("div.lazy").lazy({
    customLoader: function(element) {
        element.html("loaded by '" + element.data("loader") + "'");
    },
    anotherLoader: function(element) {
        element.html("loaded by '" + element.data("loader") + "'");
    }
});
```

### Get / Set Config
```JS
var lazy = $("img.lazy").lazy({chainable: false});
console.log(lazy.config("attribute"));
console.log(lazy.config("attribute", "new_value").config("attribute"));
```

**Comment by zspitzer** [comment]
the issue with the update was that when it runs, items in _lazyLoadImages only contains the original items values, it's missing the subsequently added values. 

I'll see if I can knock up a fiddle which reproduces the problem

**Comment by eisbehr-** [comment]
Your fiddle could not be wirking because you didn't set `chainable: false` and the `addItems` function needs an array or selector, not a single element (*maybe i should made this possible*). I've made some minor changes in your fiddle for better demonstration, but everything works well for me:

http://jsfiddle.net/3cpyz4ed/15/

**Comment by eisbehr-** [comment]
Just a Note:

I'ts wrong that i said you could not add a single element within a loop. Your wrong usage of `each` has irritate me. ;) Your function parameter `e` is not the element, it is the index (see here https://api.jquery.com/each/).

__But you really should not use `each` to add elements if possible. Use a selector, it's way faster.__

```JS
$("div.lazy-later").each(function() {
    loader.addItems($(this));
});
```

**Comment by zspitzer** [comment]
sorry, I was just quickly trying to knock out a test case which mimicked a more complex use case which included extra processing and wasn't using jquery, my bad :)

**Comment by eisbehr-** [comment]
No problem! :)
If you find a problem and can create a test-case please let me know!

**Comment by eisbehr-** [comment]
Hey again @zspitzer,

I've push a new development version `0.6.0.rc1` to feature branch. Main change ist the availability of all callbacks for custom loaders, like `beforeLoad` and `onFinishedAll`. I've even created a [demonstration / test fiddle](http://jsfiddle.net/46uqxxxv/). Maybe you like to take a look at the code and the '*how it works*' to give me some feedback?

I'll think it's work quite well and is pretty easy to use. What do you mean?

Thanks a lot!

**Comment by zspitzer** [comment]
the custom data-loader attribute is very flexible, it came in quite handy for something I was working on today

what do you think about removeItems(selector etc or empty for all) and getItems()? 

how come the  _events.* functions don't have descriptive names?

**Comment by eisbehr-** [comment]
Hello @zspitzer,

I have to think about that new function. `removeItems()` is generally the same as `destroy()` (except `autoDestroy: false`), `removeItems("selector")` could be an idea and `getItems()` could be a bit irritating, because Lazy removes all handled items from this list. So the result of this function could be unclear for some.

The events will be generated for every single instance. In javascript you can only use references within objects, so I had to wrap those events in an object. But object properties will not be minified, and so they are not public available I'll gave them short names to save filesize as most as possible.

**Comment by zspitzer** [comment]
Yep, I had them both in mind for use with `autoDestroy: false`, the main reason I wanted `getItems()` was to know if there was anything left in the queue. I have a custom loader which may queue up addtional items and I wanted to be able to decide about manually setting `autoDestroy:false`, perhaps a `queueLength()` ?

**Comment by eisbehr-** [comment]
How about to use the `onFinishedAll` event? Till it's not fired, there are Items left. :smiley:

**Comment by zspitzer** [comment]
but if `onFinishedAll` fires and `autodestroy:false` is set and then you add more items, it requires maintaining a secondary state instead of just querying actual instance

**Comment by eisbehr-** [comment]
Well, it would even work with `onFinishedAll`, but you're right, it's more complicated and requires more self-controll in own functions. I will think about it ...

**Comment by zspitzer** [comment]
what do you think about throwing an error when adding items to an instance which has been destroyed?

https://github.com/eisbehr-/jquery.lazy/blob/feature/jquery.lazy.js#L580

**Comment by eisbehr-** [comment]
Hmm, not sure about that. It's an overhead and not really necessary. I'm think about it. ;)
