### ISSUE TITLE
Images loading twice

### ISSUE THREAD

**Issue by mikeott** [eisbehr-/jquery.lazy#272]
While looking at the Network tab of the element inspector, as images with the 'lazy' class come into view they each get loaded twice. Replicated in latest versions of Chrome and Firefox.

<img src="https://rocketapps.com.au/_misc_files/waterfall.gif" style="displa:blockl;width:100%;" />

I've confirmed this happens with jpg images as well.

My js:

<pre>
`jQuery(function(jQuery) {
	jQuery('.lazy').lazy({
		effect: 'fadeIn',
		effectTime: 500,
		threshold: 0,
	});
	jQuery('iframe[data-src]').lazy();
});`
</pre>	
Reducing it to just this...
<pre>
`jQuery(function() {
	jQuery('.lazy').lazy();
});`	
</pre>	
...doesn't change anything.

We've been using this script without any drama for a long time, and this is the first time I've seen this behaviour.

**Comment by dkern** [comment]
There are multiple issues describing this. Just search for "twice". ;)

**Comment by mikeott** [comment]
@dkern Props - and I feel stupid for not checking that first. Feel free to delete this as you are correct the issue has been well documented already.
