### ISSUE TITLE
multiple instances share config values

### ISSUE THREAD

**Issue by zspitzer** [eisbehr-/jquery.lazy#30]
when you have multiple instances, it seems the configuration is shared

a quick fiddle http://jsfiddle.net/bfvspbcw/8/ 

if you click one instance: threshold is 15 and null, 
if you click two instances: both thresholds are 10 (despite lazy1 being configured as 15)

**Comment by eisbehr-** [comment]
Interessesting! I will investigate this bahvior ...

**Comment by zspitzer** [comment]
Incidentally that's why I asked about the add item exception, I set one instance to auto destroy and the other one destroyed it's self

**Comment by eisbehr-** [comment]
I solved the problem. The change will come up to the feature branch within the next commit. Thanks for you hint!

**Comment by eisbehr-** [comment]
Just to inform you, the update is available on feature branch. Feel free to test it. Thanks!

**Comment by zspitzer** [comment]
just tried it out, all works fine, thanks
