### ISSUE TITLE
image path issue

### ISSUE THREAD

**Issue by csvendsen** [eisbehr-/jquery.lazy#31]
any ideas on a fix for this im having issues with the src directory 
data-src="http://domain.com/images/image.png" does not work
data-src="../images/image.png" does not work

**Comment by eisbehr-** [comment]
Hello @csvendsen,

there is actually no source related issue. If none of your image path workes please check your script or your relative directories. Otherwise please add a bit more details here.

http://jsfiddle.net/jwwL235k/
