### ISSUE TITLE
Angularjs (ng-repeat and filters) - event to trigger _initialize

### ISSUE THREAD

**Issue by christian-beckmann** [eisbehr-/jquery.lazy#33]
Some trouble with angularjs ng-repeat and filters and _initialize event.

**Comment by eisbehr-** [comment]
Solved the problem by yourself? ;)

**Comment by christian-beckmann** [comment]
Sorry it was not an browser problem. I deal with angularjs and ng-repeat. Every time I call the lazy directive, it does not _initialize after changing the ng-repeat elements (by filters). How could I call the _initialize by angularjs directive? 

    app.directive('lazy', function ($timeout) {
        return {
            restrict: 'C',
            link: function (scope, elm) {
                $timeout(function () {
                    $(elm).Lazy({
                        bind: 'event',
                        attribute: 'data-original',
                        autoDestroy: true,
                        effect: 'fadeIn',
                        effectTime: 250,
                        visibleOnly: true,
                        defaultImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC'
                    });
                }, 0);
            }
        };
    });

**Comment by eisbehr-** [comment]
I'm not familar with angular, so I don't know what you want to archive. I'm confused about `ng-repeat` too. Do you call Lazy for an single element by repeat?

The basic handling is correct. you use `bind: 'event'` what should trigger Lazy directly. As seen here: https://github.com/eisbehr-/jquery.lazy/blob/master/jquery.lazy.js#L429 . So i think it's not a problem with the plugin. Are you sure your directive works well?

**Comment by christian-beckmann** [comment]
Ok, bind: 'event' works fine. I didn't realized it first. Thats the reason i looked for a feature to initialize the image plugin later. Angularjs calls every image with the css class "lazy". It is based on http://eshlox.net/2014/04/06/angularjs-single-page-application-and-lazy-loading-images/. 

Btw: Good work. It spend me a lot of time. And instead of this plugin http://www.appelsiini.net/projects/lazyload it works still for 1.000 images on page, without getting slow scrolling.

**Comment by eisbehr-** [comment]
Well, it's nice that it still works with 1.000 images. ;) But in your case you create 1.000 plugin instances. Thats hella slow! You should do the trick with a single instance! Mutch faster.

As said before, I don't know angular, but here an example like i thought it would works:

```JS
var lazyInstance = $(".lazy").Lazy({
    chainable: false, // IMPORTANT
    autoDestroy: false, // IMPORTANT
    bind: 'event', // IMPORTANT
    attribute: 'data-original',    
    effect: 'fadeIn',
    effectTime: 250,
    visibleOnly: true,
    defaultImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC'
});

app.directive('lazy', function ($timeout) {
    return {
        restrict: 'C',
        link: function (scope, elm) {
            $timeout(function () {
                lazyInstance.addItems($(elm));

                //  optionaly: update lazy's view afterwards, not needed if element is out of reach
                // lazyInstance.update();
            }, 0);
        }
    };
});
```

**Comment by christian-beckmann** [comment]
Nice one. It works only with lazyInstance.update(), or when scrolling first. You can see it on http://www.sosbrutalism.org/cms/15887473

**Comment by christian-beckmann** [comment]
Does addItems push images twice? Or is it like an index?

**Comment by christian-beckmann** [comment]
I reverted my changes to many instance, instead of doign addItems, wich seems to add images twice and more.

**Comment by eisbehr-** [comment]
No, this is not an index. This adds all elements you give'em. But wheres the problem? Make yourself an index. :) You could use jquery data for example.

```JS
app.directive('lazy', function ($timeout) {
    return {
        restrict: 'C',
        link: function (scope, elm) {
            $timeout(function () {
                if( !$(elm).data("lazy-added") ) {
                    $(elm).data("lazy-added", true);
                    lazyInstance.addItems($(elm));
                }
            }, 0);
        }
    };
});
```

**Comment by christian-beckmann** [comment]
Thx that's it :)

**Comment by eisbehr-** [comment]
You're welcome! I'm glad I could helped you. :smiley:
