### ISSUE TITLE
Issues with ajax

### ISSUE THREAD

**Issue by tsm91** [eisbehr-/jquery.lazy#37]
@eisbehr- so i created a new issue :)

The problem is, when show more occurs and i try to re-instantiate lazy load it will not replace `data-src` to `src` anymore if the current lazy instance auto destroys itself before ajax complete. If i scroll fast and ajax complete fires before auto destroy and i do `.addItems` to current instance it works.

so it works if in console i see:
```
#addLazyItems
#onFinishedAll
```

it doesn't work if:
```
#onFinishedAll
#addLazyItems
```

```js
export default class Comment {
  constructor() {
    this.initLazyLoad($('img.lazy'));
  }

  initLazyLoad($imgs) {
    this.lazyInstance = $imgs.Lazy({
      chainable: false,
      afterLoad(img) {
        img.removeClass('lazy');
      },
      onFinishedAll() {
        console.log('#onFinishedAll');
      }
    });
  }

  addLazyItems() {
    console.log('#addLazyItems');
    const $imgs = $('img.lazy');
    if (this.lazyInstance) {
      this.lazyInstance.addItems($imgs);
    } else {
      this.initLazyLoad($imgs)
    }
  }

  onShowMore() {
    this.showShowMoreLoader();
    $.ajax({
      type: 'GET',
      url: location.setQueryParam('page', ++config.paginate.page),
      dataType: 'json',
      success: this.onShowMoreSuccess.bind(this),
      complete: this.addLazyItems.bind(this)
    });
  }

}

```

**Comment by eisbehr-** [comment]
Hello @tsm91 and thanks for creating a new Issue ...

Well, I'm not quite sure what you want to archive with your script. I assume you want to load more images over ajax and add them to an existing lazy instance afterwards. Correct?

In your case that could have the problem, that the instance gets destroyed whenerver every element inside was loaded.

So in my opinion I would disable the auto destroy functionallity and do it manually if needed (like in a single page app, otherwise you don't need to destroy an instance). So the instance will always be available, empty or not, and you can push new elements to it every time.

It is even a good idea to update the viewport manually once you added new images. Because the user could have scroll to a new area where are new images now.

See my example below (not tested :smiley:)

```JS
export default class Comment {
    constructor() {
        this.lazyInstance = $('img.lazy').Lazy({
            chainable: false,
            autoDestroy: false,
            afterLoad(img) {
                img.removeClass('lazy');
            }
        });
    }

    addLazyItems() {
        this.lazyInstance.addItems('img.lazy')
                         .update();
    }

    onShowMore() {
        this.showShowMoreLoader();
        $.ajax({
            type: 'GET',
            url: location.setQueryParam('page', ++config.paginate.page),
            dataType: 'json',
            success: this.onShowMoreSuccess.bind(this),
            complete: this.addLazyItems.bind(this)
        });
    }

    // OPTIONAL - only for single page apps
    destroyInstance() {
        this.lazyInstance.destroy();
    }
}
```

**Comment by tsm91** [comment]
"So in my opinion I would disable the auto destroy functionallity and do it manually if needed (like in a single page app, otherwise you don't need to destroy an instance). So the instance will always be available, empty or not, and you can push new elements to it every time."

That is why the instance check, it will get undefined if destroy called.
``` js
if (this.lazyInstance) {
      this.lazyInstance.addItems($imgs);
    } else {
      this.initLazyLoad($imgs)
    }
```

but  your solution is much more concise, to destroy the lazy load instance once no more pages to load. 

and.. it works perfectly :)

p.s: not archive but achieve

**Comment by eisbehr-** [comment]
Well yes, and there is a little problem too: `destroy() != undefined`. The variable `this.lazyInstance` will still be an object after destroy. But without any events or elements. There is no way I know how the instance itself could redefine `this.lazyInstance` to `undefined` ...

**Comment by tsm91** [comment]
ahahah you are right its not possible, only by comment component

**Comment by eisbehr-** [comment]
Because of your problem it added a return to `destroy` function. Just to inform you, to redefine and check an instance you can do something like this now:

```JS
this.instance = this.instance.destroy();
if( !this.instance ) {
    console.log('instance destroyed');
}
```

**Comment by tsm91** [comment]
nice :)

in the end i ended up with a singleton instance, that i never destroy

**Comment by eisbehr-** [comment]
I's the cleaner and faster way too! :wink:

**Comment by tsm91** [comment]
By the way have  you ever considered using css transitions for fadein animations where supported? http://caniuse.com/#feat=css-transitions

Just an idea but it could be something like this:
* by default img.lazy could have `opacity: 0;`
* when `data-src` got replaced to `src` in the img.onload callback, add a `style="opacity: 1;"`

Even my chrome freezes for a few milliseconds with that jquery fadein animation :D

**Comment by eisbehr-** [comment]
Well, do it by yourself! Nothing the plugin need build-in.
(_not tested again, but someway like this should do the trick_)

```CSS
img.lazy {
    opacity: 0; 
    transition: opacity 0.1s linear;
}
```

```JS
$("img.lazy").lazy({
    afterLoad: function(element) {
        element.css("opacity", 1);
    }
});
```

**Comment by tsm91** [comment]
ahhh really, the hooks :)
