### ISSUE TITLE
Doesn't work with Flexbox style layouts

### ISSUE THREAD

**Issue by xstortionist** [eisbehr-/jquery.lazy#40]
.layout-container {
        height: 100vh !important;
        position: relative !important;
        width: 100% !important;
    }
    .layout-container {
        height: 100%;
        position: absolute;
        width: 100%;
    }
    .layout-content {
        display: flex;
        flex-direction: column;
        height: 100%;
        overflow-x: hidden;
        overflow-y: auto;
        position: relative;
        width: 100%;
    }
    .page-content {
        display: inline-block;
        flex-grow: 1;
        overflow-x: hidden;
        overflow-y: auto;
        z-index: 1;
        width: 100%;
    }

Doesn't work when using this style of layout. Has issue with overflow-x and y.

**Comment by eisbehr-** [comment]
Hello @xstortionist !

Thanks for your feedback. I'm not really into flexbox and could not recreate your problem without the html/js code. Could you set up a [jsfiddle](http://jsfiddle.net)? Maybe it is only a configuration option.

Greets,
Daniel

**Comment by xstortionist** [comment]
Hi @eisbehr- 

Thanks for the response. The majority of mobile apps being built with flexbox style layouts now. I'll get something up on jsfiddle soon so you can see.

Thanks!

-Derek

**Comment by eisbehr-** [comment]
I'll close this for now. Feel free to reopen / answer this issue.
