### ISSUE TITLE
getItems() can returned handled items during processing

### ISSUE THREAD

**Issue by zspitzer** [eisbehr-/jquery.lazy#41]
at the moment, getItems() just returns the internal items, without filtering out the handled items

thus, if you call getItems() in a custom loader before _lazyLoadItems has looped thru everything
and then subsequently filtered out the handled items, you will see some already handled items

**Comment by eisbehr-** [comment]
Hey @zspitzer !

Well, yes. You're right at this point! But I think on the other hand it is even more complex. If I filter the items in `getItems()` by the handling-marker, it is possible that there are some Items missing which currently not finished but already marked as handled.

So what is the best way to handle it?! In the current case, you can filter the Items by yourself. If I change the behavior there are possible some items to mutch removed ... I'm actually not sure about that. :)

Or I need to implement a second marker / state to differ by `in handling` and `handled`.

Greets,
Daniel

**Comment by zspitzer** [comment]
handled could have multiple states?

1 for loading, true for loaded, both which evaluate to true

then getItems() could return only loaded items and getItems(true) returns both

**Comment by eisbehr-** [comment]
I think I'll implemnt it somhow like this with the next update. It's a special usecase, but why not. :)

**Comment by zspitzer** [comment]
I have been playing with this today, I think _reduceAwaiting might be a better place to eliminate handled items

**Comment by eisbehr-** [comment]
Hmm, I think not really. `_reduceAwaiting` is trigered for every single loaded image. So the filter would be executed for every single image. Actully the filter it only triggered once for ever throttled scroll event. Way better performance this way.

**Comment by zspitzer** [comment]
but if _awaitingAfterLoad is 0?

**Comment by eisbehr-** [comment]
This would cause the behavior, on pages with many images and you keep scrolling, the `_awaitingAfterLoad` will never (_only at the end_) be zero and the filter would never get triggered and so the `getImages` function will still return wrong items. :wink:

**Comment by zspitzer** [comment]
`onFinishedAll` is only triggered in `_reduceAwaiting`, but the removal of handled items may occur after all  the `_reduceAwaiting` calls have already completed

**Comment by eisbehr-** [comment]
I'm not sure what's your point in the last post?!

**Comment by eisbehr-** [comment]
Hey @zspitzer,
the problem shoould be fixed within [1.6.6](https://github.com/eisbehr-/jquery.lazy/releases/tag/1.6.6)!
