### ISSUE TITLE
Background images don't load when URL contains a space

### ISSUE THREAD

**Issue by pburke** [eisbehr-/jquery.lazy#43]
When trying to lazy load a background image, the script adds the CSS background-image property without quoting the URL. This prevents the image from loading.

**Comment by pburke** [comment]
PR #44

**Comment by eisbehr-** [comment]
Hello @pburke and thanks for your support!

But this is not true to me. I never got problems at all. As seen [here](https://www.w3.org/TR/CSS2/syndata.html#value-def-uri) it's not necessary by W3C to use quots in url definitions. Could you apply an example / fiddle to show the problem and deliver some browser / version inforamtion, so I will understand your intention or could investigate the problem?!

Thanks!

**Comment by eisbehr-** [comment]
Well, moment. Maybe. Do mean you use unescaped spaces in your url's? And not like "%20"? :smile:

**Comment by pburke** [comment]
Here's a pen with an example:
http://codepen.io/anon/pen/grrqyW

This particular image also has parentheses in the filename, but as the example shows, the URL needs to be fully escaped to work. The spec might not require quotes in URL definitions, but don't you agree it's a good idea? Can't hurt anything, and it might save your users some frustration.

**Comment by eisbehr-** [comment]
No, you're right. I just like to understand problems before I fix them. ;)
And I'll never came across such problems till now. So thanks for your explaination. I will merge your pr within the next update. This may take some days, but i will do. 

Thanks!

**Comment by pburke** [comment]
Thank you!
