### ISSUE TITLE
Examples on you website - Basic Usage - Needs to be more explicit!

### ISSUE THREAD

**Issue by phpcoder2011** [eisbehr-/jquery.lazy#48]
Hi. Just want to note (as a very first time user of lazy loading technique and your plugin in particular) that it took me ALMOST 2 HOURS to realize that i need to prepare images in specific, non-standard way. In the "Basic Usage" of the "Get Started" section it is NOT obvious for a first time visitor what "Just prepare your elements" means. I thought it means - just add your img tags or something. So i just created my test.html page, included all required scripts, added a lot of "img" rows and couldn't realize why it is not working. The only way i finally realized how everything works is by disabling javascript and seeing what happens before jQuery.lazy() plugin kicks in. So in short - just a simple suggestion - please explicitly add IN THE "Basic Usage" example of how img tag should be prepared. I admit i was lazy to read till the end of the "Getting Started" section, but "Basic Usage" section without providing an example of img tag is misleading IMO, so without knowing it i though the instruction was complete.

**Comment by eisbehr-** [comment]
Well, there actually **is** an example `img` tag displayed in the `basic usage` area. Just click on the `html` tab and there you go. Even here on GitHub there is an example under `basic usage`. Keep your eyes open, it's all there. :wink:

Great you got it working anyway ...
