### ISSUE TITLE
autoDestroy kills triggers for all Instances

### ISSUE THREAD

**Issue by taleteller** [eisbehr-/jquery.lazy#49]
I was building a page with two instances of Lazy, only slightly different by one event handler. However when I was loading the page showing elements of instance one, scrolling towards the elements of instance two, the latter ones never appeared. Same went if i tried the other way around. 

The problem was fixed after setting: `autoDestroy: false` for both instances. Obviously when all items of a given instance are displayed the Lazy instance destroys itself. But it also destroys the scroll triggers for any other instance.

Happens to me using jquery.lazy-master under jQuery 1.11.3 on any brower.

**Comment by zspitzer** [comment]
can you create a fiddle? you could fork the one in #30 as a starting point (update the script src, it points  to the feature branch)

**Comment by eisbehr-** [comment]
Well, he's right. The problem ist, that `destroy()` (as called on `autoDestroy`) removes all events by the namespace `.lazy`. There is no check or handling for multiple instances. The problem would be solved, if you include two script files with different names on [line #550](https://github.com/eisbehr-/jquery.lazy/blob/master/jquery.lazy.js#L550). :smile: But that should not be the workaround.

Maybe I implement an "instance count" witch will be added to the namespace. Or something else. Had to think about that.

**Comment by christian-beckmann** [comment]
Me too. I wanted to load visible images by a default Lazy loading configuration. But invisible images, which should be visible by "mouseenter" trigger a custom Lazy loading. Autodestroy does not make a difference between those instances. 

I looked for an custom event triggering those lazy loading without doing it that way:

`
            var $lazyImages = $('img[data-original]').filter(':visible');
            $lazyImages.Lazy({
                attribute: 'data-original',
                autoDestroy: false,
                effect: 'show',
                effectTime: 0,
                visibleOnly: true
            });

            $('.mainContent .profil').on('mouseenter', function () {
                var $lazyImages = $(this).find('[data-original]');
                if ($lazyImages.length) {
                    $lazyImages.Lazy({
                        bind: 'event',
                        attribute: 'data-original',
                        autoDestroy: false,
                        effect: 'fadeIn',
                        effectTime: 250,
                        visibleOnly: true
                    });
                }
            });

`

I try to trigger it that way:

`
            var $lazyImages = $('img[data-original]').filter(':visible');
            $lazyImages.Lazy({
                attribute: 'data-original',
                autoDestroy: false,
                effect: 'show',
                effectTime: 0,
                visibleOnly: true
            });

                
                    $('img[data-original]').not(':visible').Lazy({
                        bind: 'custom-lazy-load',
                        attribute: 'data-original',
                        autoDestroy: true,
                        effect: 'fadeIn',
                        effectTime: 250,
                        visibleOnly: true
                    });

            $('.mainContent .profil').on('mouseenter', function () {
$(this).find('[data-original]').trigger('custom-lazy-load')
           });

`

What do you think?

**Comment by eisbehr-** [comment]
Hello @christian-beckmann 
Please create an own issue for your question! I'll delete your post here for now ...

**Comment by zspitzer** [comment]
for debugging single page apps, it would be nice to be able to pass in something meaningful for the namespace, like cid in backbone.js

**Comment by eisbehr-** [comment]
There is a thing for this. It's the instance name. But the problem is, that it is actually not configurabe from the "outside". I should have to make this within an update ...

**Comment by eisbehr-** [comment]
I fixed this issue in [srcset branch](https://github.com/eisbehr-/jquery.lazy/tree/srcset) and will be added to the master within the next update. Feel free to give it a try. Thans for reporting.

**Comment by razola** [comment]
I would also need a fix for this. Is the plan that the srcset branch will replace the current master branch? If so I might as well use that one, even though I don't use responsive images..

**Comment by eisbehr-** [comment]
Hello @razola,

yes, the `srcset` branch will be merged to the master as the next version. But the branch is actually not completly tested. The auto destroy problem is fixed, but there were made some more changes in the branch, like new features. So is should be working, but no guarantee. I think the updated will be released within the next 1-2 weeks.

If you want to use the actual `srcset` branch, I would recommend to use this particular version of Lazy, because it is an early state, with the auto destroy fixed:
https://github.com/eisbehr-/jquery.lazy/blob/140bc715ac202d8d37d9e8559c7209d057c01ca6/jquery.lazy.js

**Comment by razola** [comment]
@eisbehr- thanks for the quick reply!

I'll use the version you specified until the next release.
