### ISSUE TITLE
Tab container and loading

### ISSUE THREAD

**Issue by kprovance** [eisbehr-/jquery.lazy#51]
I have a unique situation here, maybe.  I have a tab interface which contains - optionally - images.  The open tab window (divs that hide and show based on the clicked tab) that contains an image loads when scrolled into view.  Now, if I click on another tab, the image there does not load until I scroll the page a bit.  I saw this (http://jquery.eisbehr.de/lazy/example_load-elements-by-events), thought maybe I could force load the image on the tabs click event.  That example however would load the rest of the images not yet on the screen, which I'd rather not do.  Is there something a little more precise that could be done?

Here is my JS:

```
    $.req.imageLazyLoad = function() {
        var effect      = $('body').data('lazyload-effect');
        var effectTime  = $('body').data('lazyload-time');
        
        $('.req-lazy').lazy({
            effect: effect,
            effectTime: effectTime,
            threshold: 0,
            
            afterLoad: function(element){
                setTimeout(function() {
                    element.addClass('load-finished');
                }, effectTime);
            }
        });
    };
```

**Comment by kprovance** [comment]
You know, as soon as I ask for help, I find the answer.  Every.  Time.  Woes of a developer, I guess.

instance.update() was what I needed.

Cheers.

**Comment by eisbehr-** [comment]
I'm glad you found the solution by yourself! :wink:

**Comment by kprovance** [comment]
Again, as usually happens after I ask someone else.  Great plugin you have here, mate.  Using it in a WordPress theme, works like a charm.  Thanks.  :)
