### ISSUE TITLE
item loop in _lazyLoadItems caches item length can cause exception

### ISSUE THREAD

**Issue by zspitzer** [eisbehr-/jquery.lazy#58]
Because the length of the item array is being cached, it's possible for an exception to be triggered in `_isInLoadableArea`, "element is undefined" if a loader with a callback is used and the size of the item array is reduced by another round of `_lazyLoadItems` being executed which removes one or more items from the item array, whilst waiting for the loader to return.

https://github.com/eisbehr-/jquery.lazy/blob/master/jquery.lazy.js#L305

**Comment by eisbehr-** [comment]
Hi @zspitzer,

I'm actually not sure, how this could happen. Inside the `for` loop the object is given by `items[i]` to the inner function. This should mean, even if the object would be removed from the `items` array, it is still available to the inner loop. So `_isInLoadableArea` should still work. I have to test this somehow ...

Do you have an example where this happens to you? Can you create a fiddle?

And if you have such problem, do you already got a workaround?

Thank you so far!

**Comment by zspitzer** [comment]
I'm on holidays and thus dad duty at the moment , so i haven't had time to knock out a fiddle.
the customer loader was async as it was doing some network calls , I think _lazyLoadItems might of been  triggered again whilst waiting for the server to respond.

I encountered this with some content in a dashboard which involves nested instances of lazy loaders, I was previously having issues with the destroy and namespaces which you fixed recently and thought I'd try it out and encountered the exception.

but the fix is dead simple
`for( var i = 0, l = items.length; i < l; i++ )`
becomes
`for( var i = 0; i < items.length; i++ )`

**Comment by eisbehr-** [comment]
Ahh well, yes, of course. I was thinking that would work. But on JS it's working this way. :wink: 
I will make this little change within the next update ...

**Comment by eisbehr-** [comment]
fixed as of [1.7.3](https://github.com/eisbehr-/jquery.lazy/releases/tag/1.7.3)
