### ISSUE TITLE
Base case Initialization issue

### ISSUE THREAD

**Issue by lawrencealexander10** [eisbehr-/jquery.lazy#59]
Hi,
I am trying to initialize lazy after page load and have images load when visible in the viewport, however despite the documentation after the page loads, all the images begin to load on the page even when not in the viewport. It loads images from the top of the page and cascades down regardless of where I am. I've tried adjusting various parameters such as threshold and setting visible only to no avail.
Interestingly, on page load, if my viewport is at the bottom of the page only those images load and as I scroll upward, the page exhibits the behavior I would expect from this library. (The images load consecutively after upward scroll). Do you know of a solution/ Is there a reason to explain this behavior?

Thanks

**Comment by lawrencealexander10** [comment]
I created a gist with my code that exhibits the unusual behavior: https://gist.github.com/lawrencealexander10/ccc53772446f2cf239e990f9b2342db3
I tried it another computer and it exhibited the same behavior.

When attempting a jsfiddle with the same code in the gist, it worked to the spec so I am unsure what the issue is.

Thanks

**Comment by eisbehr-** [comment]
Hmm, as you said, the code workes fine and I see no problems there. Have you ever tried to log the lazy loading and see if Lazy really loads all images at start? You could do it like this:

```JS
$(function() {
    $('.lazy').Lazy({
        afterLoad: function(element) {
            console.log(element.attr("src"));
        }
    });
});
```

**Comment by lawrencealexander10** [comment]
Yes I have, and the console logs all elements immediately on page load. The only time this doesn't happen is when my viewport is on the bottom of the page on load. As I scroll up the images lazy load. I'm not sure why this occurs and the inverse doesn't

**Comment by eisbehr-** [comment]
Finally I found your problem!
You didn't set a `doctype` in your page. Just add `<!DOCTYPE HTML>` to the first line and everything works fine! Without this jQuery can't detect the dimensions. And another hint. The `<style>` tag should be placed in `<head>`. Since CSS3/HTML5 it is possible to place those style tags everywhere, but then it should be `scoped` once.
