### ISSUE TITLE
Possible to lazy load images within a slider?

### ISSUE THREAD

**Issue by xstortionist** [eisbehr-/jquery.lazy#62]
Hello,

This isn't a bug as much as it is just a simple question. Is it possible with this plugin to lazy load images that are within a javascript slider?

Thanks!

**Comment by eisbehr-** [comment]
Hello @xstortionist ,

sure, it is possible. But there are different ways to do it, this belongs to what you want to do. Like to load the images completely on start, or only on slide, ect.
