### ISSUE TITLE
lazy function is not getting recognised

### ISSUE THREAD

**Issue by anshudaur** [eisbehr-/jquery.lazy#64]
Hi,I need help with lazy loading. I have tried your code for lazy loading. I have kept my div inside a div with class lazy and applied css style of display:none.

```JS
$(function() {
    $(".lazy").lazy({
        console.log("inside lazy function");
        afterLoad: function() {
            console.log("data is about to be loaded");
            $('.lazy').css("display","block");
        },
        onError: function() {
            $('.lazy').css("display","block");
            console.log('onError of lazyLoad');
        },
        onFinishedAll: function() {
            $('.lazy').css("display","block");
            console.log('lazy loading finished');
        }
    });
});
```

Also, i have called `<script src="/cs/mysyf/jquery.lazy.min.js" / >` befor ethe script.
And i am not getting any thing in the logs related to this

**Comment by eisbehr-** [comment]
Hello @anshudaur !

Well, I can tell you for now that your posted code **can't** work. Because it is invalid JavaScript. You cant place `console.log` directly inside an `object`.

Beside this your code has another problem. You set `display` to `block` after every `load` or `error`. This means that even elements that are not handled by now will be set to this. You shuld instead use the `element` parameter of the callback to only set this to the correct items. But it is not needed in `onFinishedAll`.

```JS
$(function() {
    $(".lazy").lazy({
        // console.log("inside lazy function"); <-- this line is not allowed !
        afterLoad: function(element) {
            element.css("display", "block");
            console.log("Dealer locator data is about to be loaded");
        },
        onError: function(element) {
            element.css("display", "block");
            console.log('onError of lazyLoad');
        },
        onFinishedAll: function() {
            console.log('lazy loading finished');
        }
    });
});
```

That are all problems I can see for now. That should work in general.

**Comment by anshudaur** [comment]
HI, i tried your change, but the function call is itself not happening

**Comment by eisbehr-** [comment]
Well, then I need to see your whole code. It is impossible to tell whats wrong without seeing the problem. Please use [jsfiddle](https://jsfiddle.net/) to create an example reproducing the problem.

**Comment by anshudaur** [comment]
Hi, thanks for your time. The link for jsfiddle is : https://jsfiddle.net/oge0qs3a/1/

**Comment by eisbehr-** [comment]
I have to ask ... What are you trying to do?
Because this is completly wrong usage. Are you familar with the principle of _lazy loading_?

**Comment by anshudaur** [comment]
Hi, Ok i will explain you what i want to do. My page is pretty big and the bottom of it, i am getting data dynamically which is making my page slow. SO i want to implement lazy loading which according to me is not loading the element untill you scroll down to the page where your element exists. That's right , right?

**Comment by eisbehr-** [comment]
Well, basically. `Lazy` can load images by default (_without plugins_) when scrolling to them. It is even possible to load more data on scroll, like over `ajax`.

But it is not possible as you did. Think about it by yourself. Everything in the `html document` will be loaded when the browser load it. So placing your `ul` inside a `div` will not prevent the browser from loading it. You will only _show_ the element, when the user scrolls to it. 

For lazy loading content like this you have to do a bit more work. I wrote an example some time ago on [stackoverflow](http://stackoverflow.com/questions/38760148/jquery-lazy-plugin-is-not-loading-my-li-contents/38761668#38761668). This should give you an idea what you have to do.

**Comment by anshudaur** [comment]
You are right .. I will take a look into this. Thanks.

**Comment by anshudaur** [comment]
Hey it worked. Thanks a ton for your patience and solution :P
