### ISSUE TITLE
unloading support

### ISSUE THREAD

**Issue by zspitzer** [eisbehr-/jquery.lazy#66]
What do you think about adding unloading support? 

Just keep track of any loaded elements and fire a handler when they are off screen so they can be lazy unloaded

**Comment by eisbehr-** [comment]
Hello @zspitzer,

I'm not sure for what such functionality is useful? Do you have an example for me, where this would be needed?

And I'm already see the disadvantage of this. Mention a gallery with hundreds or thousands of images (_what I actually know is used out there many times_). So Lazy have to keep all this images inside the instance to watch them over and over again, and not remove the elements after handling. So it would be a huge performance drop.

**Comment by eisbehr-** [comment]
Closed because of missing response.
