### ISSUE TITLE
requirejs - jquery - jquery-lazy

### ISSUE THREAD

**Issue by cormorano71** [eisbehr-/jquery.lazy#69]
I've used `jquery-lazy` with requirejs. It seem to work but when I use the back button (e.g. loading of scripts via cache in chrome) seem that `jquery-lazy` can't detect window `onload`.

I've tryed this patch, and it seem to work properly:
```JS
windowLoaded = (window.document.readyState!=="loading");  // instead of false
```

How I've used requirejs:
```HTML
<script src="/js/require.min.js"></script>

<script>
requirejs.config({
"baseUrl" : "/js/",
"paths" : { "jquery" : "jquery-1.12.3.min" },
"shim": {
	"lazyload": {
		"deps": ["jquery"],
		"exports": "jQuery.fn.lazy"
	}
}
});
</script>

<script>
	require(["jquery","lazyload"], function($) { 
		$("img.lazy").lazy({
			effect: "fadeIn",
			effectTime: 1000,
			threshold: 0
		});
	});
</script>
```

**Comment by eisbehr-** [comment]
Hello @cormorano71,

is this a real problem of Lazy, or is it a problem of jQuery/RequireJS not handling the load correct? The only reason your patch works, is because you assume everything as not `loading` to be valid. Which could match pretty often and might not be the correct state.

If I got some time, i will try to investigate on this. But as I said, I'm pretty sure that is not a problem of this plugin, when jQuery is not able to recognize the correct state.

**Comment by cormorano71** [comment]
I think the problem was into lazy.The question was: what happen if you load Lazy after window load.
The row     $(window).on("load", function() { windowLoaded = true; });doesn't work because window was loaded and doesn't fire any more the load event 
I don't understand the exact state required by lazy then my patch may be wrong,I think it's better to replace with window.document.readyState!=="complete"





----Messaggio originale----

Da: "Eisbehr" <notifications@github.com>

Data: 23/11/2016 19.54

A: "eisbehr-/jquery.lazy"<jquery.lazy@noreply.github.com>

Cc: "cormorano71"<riccardo.marangone@libero.it>, "Mention"<mention@noreply.github.com>

Ogg: Re: [eisbehr-/jquery.lazy] requirejs - jquery - jquery-lazy (#69)




Hello @cormorano71,

is this a real problem of Lazy, or is it a problem of jQuery/RequireJS not handling the load correct? The only reason your patch works, is because you assume everything as not loading to be valid. Which could match pretty often and might not be the correct state.

If I got some time, i will try to investigate on this. But as I said, I'm pretty sure that is not a problem of this plugin, when jQuery is not able to recognize the correct state.

**Comment by eisbehr-** [comment]
Ahh, okay. Well, there is a configuration property to let Lazy don't wait for window loading. Use the `bind` parameter and set it to `event`. This will start Lazy instantly. So you can the control the exact entry point on your own.

```JS
$("img.lazy").lazy({
    bind: "event", // add this line
    effect: "fadeIn",
    effectTime: 1000,
    threshold: 0
});
```

More information can be found in the [documentation](https://github.com/eisbehr-/jquery.lazy#configuration-parameters).
