### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by fariskas** [eisbehr-/jquery.lazy#71]
having problems adding a placeholder image.
can't seem to have it show during loading / delay?
tried using image from different sources too

>    ` jQuery(".lazy").lazy({
        effect          : "fadeIn", 
        effectTime      : 500,
        delay           : 500,
        scrollDirection : 'vertical',
        visibleOnly     : true,    
        placeholder     : "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAQAAADTdEb+AAACIElEQVR42u3SQQ0AAAgDsc2/aDBBwqeVcLlmAudqLIyFsTAWGAtjYSwwFsbCWGAsjIWxwFgYC2OBsTAWxgJjYSyMBcbCWBgLjIWxMBYYC2NhLDAWxsJYYCyMhbHAWBgLY4GxMBbGAmNhLIwFxsJYGAuMhbEwFhgLY2EsMBbGwlhgLIyFscBYGAtjgbEwFsYCY2EsjAXGwlgYC4yFsTAWGAtjYSwwFsbCWGAsjIWxwFgYC2NhLBEwFsbCWGAsjIWxwFgYC2OBsTAWxgJjYSyMBcbCWBgLjIWxMBYYC2NhLDAWxsJYYCyMhbHAWBgLY4GxMBbGAmNhLIwFxsJYGAuMhbEwFhgLY2EsMBbGwlhgLIyFscBYGAtjgbEwFsYCY2EsjAXGwlgYC4yFsTAWGAtjYSwwFsbCWGAsjIWxwFgYC2OBsTAWxsJYxsJYGAtjgbEwFsYCY2EsjAXGwlgYC4yFsTAWGAtjYSwwFsbCWGAsjIWxwFgYC2OBsTAWxgJjYSyMBcbCWBgLjIWxMBYYC2NhLDAWxsJYYCyMhbHAWBgLY4GxMBbGAmNhLIwFxsJYGAuMhbEwFhgLY2EsMBbGwlhgLIyFscBYGAtjgbEwFsYCY2EsjAXGwlgYC2MZC2NhLIwFxsJYGAuMhbEwFhgLY2EsMBbGwlhgLIyFscBYGAtjgbEwFsYCY2EsjAXGwlgYC4yFsTAWGAtjYSwwFsbCWGAs/i1czywQSMCnqQAAAABJRU5ErkJggg==",
        afterLoad: function(element)
        {
            element.removeClass("loading").addClass("loaded");
        }
    });`

**Comment by eisbehr-** [comment]
Hello @fariskas,

I don't see any problem here. Maybe you are want to use `defaultImage` instead of `placeholder`. The second one will only be set on loading, but it seems you want a default image instead.

[Try this for example.](https://jsfiddle.net/sbutzs2p/)
