### ISSUE TITLE
lazy load script tag not working 

### ISSUE THREAD

**Issue by meandkareem** [eisbehr-/jquery.lazy#74]
I Added this tag and plugin for lazy script ... 
but nothing happens ... Do  I Need to do something more ?
<script data-src="//content.jwpl....." type="text/javascript"></script>

**Comment by eisbehr-** [comment]
Hi @meandkareem,

no, not really. You need to include the js file of Lazy, and the plugins file too, because `script` loading is a plugin of Lazy. And afterwars you need to initialize Lazy too, just as for `images`.

```JS
$("script").Lazy();
```

I made a [working fiddle](https://jsfiddle.net/pcLs98ch/) for you.
