### ISSUE TITLE
Add 'imageBase' config in 'picture' plugin

### ISSUE THREAD

**Issue by eisbehr-** [eisbehr-/jquery.lazy#76]
Let Lazy correct `srcset` and `src` in `picture` plugin with a given `imageBase` parameter on initialization automatically.

**Comment by eisbehr-** [comment]
Maybe think about `effect` too ...

**Comment by COderrrTUT** [comment]
good job

**Comment by eisbehr-** [comment]
Done in release [1.7.6](https://github.com/eisbehr-/jquery.lazy/releases/tag/1.7.6)!
