### ISSUE TITLE
Options "threshold" not work, default lazy load always load all lazy elements

### ISSUE THREAD

**Issue by chan493** [eisbehr-/jquery.lazy#77]

**Comment by eisbehr-** [comment]
Hello @chan493 

I'm pretty sure that this is not a problem of Lazy, it's most of the time users requests things like this, that it is wrong usage. ;) Please create a [jsfiddle](http://jsfiddle.net) recreating the problem. I will take a look then.

**Comment by eisbehr-** [comment]
Closed because of missing user input.
