### ISSUE TITLE
I cannot run the lazy load on div background images

### ISSUE THREAD

**Issue by jasomdotnet** [eisbehr-/jquery.lazy#78]
This is my code:

http://pastebin.com/H1ikvc2B (I cannot past it right here because github brokes the code)

Where's the mistake?

**Comment by eisbehr-** [comment]
Hello @jasomdotnet 

you've included the wrong file. YOu added the plugins of Lazy only, but not lazy itself.

```HTML
<!-- change -->
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.lazy/1.7.4/jquery.lazy.plugins.min.js"></script>

<!-- to -->
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery.lazy/1.7.4/jquery.lazy.min.js"></script>
```

That's it! Everything else looks fine!

**Comment by jasomdotnet** [comment]
aha. btw you are pretty fast :)

**Comment by jasomdotnet** [comment]
Ok, It works. Really stupid mistake :)
