### ISSUE TITLE
Serious problem

### ISSUE THREAD

**Issue by COderrrTUT** [eisbehr-/jquery.lazy#82]
I tried to add the IMG element to the page with Ajax and added class = lazy to img, data-src = "xx.jpg"". But she didn't work.
Hope to get your help.Thanks,; -)

**Comment by eisbehr-** [comment]
Hello @COderrrTUT 

This is not a problem, this is just wrong usage imo. When using AJAX to add images, you need to create the instance of Lazy afterwards, or add the new elements dynamically to an existing Lazy instance with the use of `public functions` (more details on the project page).

Then you can use AJAX loaded elements too ...

**Comment by eisbehr-** [comment]
Seems to be no problem anymore ... closed!
