### ISSUE TITLE
license confused

### ISSUE THREAD

**Issue by codigoart** [eisbehr-/jquery.lazy#83]
hello i just find this amazing pluggin at google but im confused about: licenseLazy is dual-licensed under MIT and GPL-2.0 license.
Does this means i have to follow both terms of each license or i can choose 1 ? 
Why not make mit license only? people do not like GPL-2 because we are forced to rls our code.

Thanks

**Comment by eisbehr-** [comment]
Hello @codigoart,

no, that means you can choose one license of both you want to use. This is a common type of licensing. So either choose GPL or MIT, whatever fit your needs.
