### ISSUE TITLE
Reload Errored Out or Failed Images 

### ISSUE THREAD

**Issue by yugakiran** [eisbehr-/jquery.lazy#84]
Sometimes unstable network may trigger an image loading error.
How can we reload or refresh the images which are failed to load.

**Comment by eisbehr-** [comment]
Hello @yugakiran 

Well, an images what could not be loaded will be handled as error. Not only by Lazy, browsers will do the same. The image will be ignored after first attempt. So you will need to trigger some loading again programmatically.

Lazy will not update the element, if an error ocurs while loading. This means, you could add the image again to the queue, maybe with a short delay. The following code is not testet, but may give you an hint of how to implement such feature.

```JS
var instance = $('.lazy').Lazy({
    chainable: false,
    onError: function(element) {
        // remove the lazy data attributes to handle again
        element.removeData(instance.config('handledName'));

        // add the item back to lazy queue
        setTimeout(instance.addItems, 1000, element);
    }
});
```
