### ISSUE TITLE
Killing of existing instance

### ISSUE THREAD

**Issue by mspanish** [eisbehr-/jquery.lazy#85]
Hi there - great plugin! My script switches out the loading when you select a new json file via the menu - loading new images, which are drawn, not just loaded - I use a custom loader.

I can't seem to kill off the existing instance - I've tried naming the instance, then instance.destroy() before loading the new data and drawings - but the other ones keep trying to load & draw.

Any advice?  Thanks in advance!

**Comment by eisbehr-** [comment]
Hi @mspanish 

Could you show me your code, especially the lazy instance you use and how you try to destroy it? It could just be some simple error, but I would need some details. ;)

**Comment by mspanish** [comment]
Hello - thanks again - got it working! This is the code that works for me:

` var instance =  $(".lazy").data("plugin_lazy");
  	instance.destroy();`

**Comment by mspanish** [comment]
I'll be delighted to send you a link once my project is live - this script will be awesome for it 👍

**Comment by eisbehr-** [comment]
Thats one way! ;)
I was thinking you might have forgotten the `chainable: false` config parameter. Then you can set the `instance` variable just on initializing Lazy. Somehow like this:

```JS
var instance = $(".lazy").Lazy({chainable: false});
// ...
instance.destroy();
```

But I'm glad it worked. Looking forward for your project!
