### ISSUE TITLE
[Feature request] Gemini Scrollbar support

### ISSUE THREAD

**Issue by Kristinita** [eisbehr-/jquery.lazy#88]
### 1. Request

It would be nice, if JQuery Lazy will support [**Gemini Scrollbar**](https://github.com/noeldelgado/gemini-scrollbar).

### 2. Justification

I think, that default browser scrollbars have a bad design, so I use custom scrollbar for my sites.

Gemini Scrollbar — scrollbar, that works for me without bugs. With other custom scrollbars I have bugs:

1. [**Malihu scrollbar**](http://manos.malihu.gr/jquery-custom-content-scroller/) — [**find text bug**](https://github.com/malihu/malihu-custom-scrollbar-plugin/issues/486#issuecomment-298243647),
1. [**NiceScroll**](http://areaaperta.com/nicescroll/) — same problem.

Another scripts for custom scrollbar can't replace for me native browsers body scrollbar.

### 3. Settings

For example,

1. Page of my site: + Gemini, - JQuery Lazy — **<http://kristinita.ru/Sublime-Text/SashaSublime>**,
1. I reduced the code of my page: + Gemini, + JQuery Lazy — **<http://cssdeck.com/labs/full/bspxx5cn>**,
1. Source of reduced page — **<http://cssdeck.com/labs/bspxx5cn>**.

### 4. Steps to reproduce

I open page **<http://cssdeck.com/labs/full/bspxx5cn>** in Firefox or Chrome → I scroll page.

### 5. Actual behavior

If JQuery Lazy enable for me and if I scroll page, images don't displayed for me:

![Actual](http://i.imgur.com/wsUesEd.png)

### 6. Expected behavior

If JQuery Lazy disable for me or if I resize my page use any methods, images displayed for me:

![Expected](http://i.imgur.com/PeoDHE4.png)

### 7. Not helped

If I use JQuery Lazy alternatives — [**LazyLoad**](http://www.appelsiini.net/projects/lazyload), [**LaziestLoader**](https://sjwilliams.github.io/laziestloader/), [**Unveil.js**](https://github.com/luis-almeida/unveil), — I have a similar problem with Gemini Scrollbar.

Thanks.

**Comment by eisbehr-** [comment]
Hello @Kristinita 

It's not needed to implement anything. Everything you need is already there. You will just need `getViewElement` by gimini scrollbar and pass this to your Lazy instance:

```JS
// create your gimini instance
var scrollbar = new GeminiScrollbar({
    element: document.querySelector('#your-element'),
}).create();

// pass the created view element to Lazy
$("img").Lazy({
    appendScroll: $(scrollbar.getViewElement())
});
```

Thank you for your request!

**Comment by Kristinita** [comment]
@eisbehr- , thanks, it works for me!

But JSLint show an error: `'scrollbar' used out of scope`.

Thanks.

**Comment by eisbehr-** [comment]
Possible, but thats belongs to your code. That should not be a general problem, it seems more that your script is not correctly structured.

**Comment by Kristinita** [comment]
## 1. Problem

If I use JQueryLazy + Gemini Scrollbar and if I scroll my page, scrollbar outside of the screen.

![Demo](http://i.imgur.com/8aGB0wH.gif)

How I can use one of [**callback functions**](http://jquery.eisbehr.de/lazy/example_callback-functions) with method [**update**](https://github.com/noeldelgado/gemini-scrollbar#basic-methods) of Gemini Scrollbar?

### 2. Settings

My script:

```javascript
window.onload = function() {
    if (window.matchMedia("(min-width: 60rem)").matches) {
        // For PC
        var pcscrollbar = new GeminiScrollbar({
            element: document.querySelector("main"),
            autoshow: true,
            forceGemini: true
        }).create();

        $("img").Lazy({
            appendScroll: $(pcscrollbar.getViewElement())
        });
    } else {
        // For Mobile
        var mobilescrollbar = new GeminiScrollbar({
            element: document.querySelector("body"),
            autoshow: true
        }).create();

        $("img").Lazy({
            appendScroll: $(mobilescrollbar.getViewElement())
        });
    }

};
```

+ Updated page — **<http://cssdeck.com/labs/full/snssbxpd>**,
+ Source of page — **<http://cssdeck.com/labs/snssbxpd>**.

Thanks.

**Comment by eisbehr-** [comment]
I'm not sure waht you want to know now. If you have problems with gimini, you should ask them for help?! I didn't knew this library until today.

To execute `update` function of gimini in a callback of `Lazy` is pretty easy. For example with `afterLoad`:

```JS
$("img").Lazy({
    appendScroll: $(pcscrollbar.getViewElement()),
    afterLoad: function() {
        pcscrollbar.update();
    }
});
```
