### ISSUE TITLE
Loading images inside tabs

### ISSUE THREAD

**Issue by myorangeca** [eisbehr-/jquery.lazy#89]
Maybe I have missed it, but was looking for a way to load images that are residing inside tabs with custom scroll plugins like slimscroll. I can get them to load by changing the "appendScroll" parameter to $('.slimScrollDiv > :first-child'); but it still forces me to scroll to load the image. Is there a way I can load the images that are visible on active tab without having to scroll first?

**Comment by eisbehr-** [comment]
Hello @myorangeca 

I think you're seraching for the `.update()` public function of Lazy. Calling this after a tab change will load the initial images without scrolling.
