### ISSUE TITLE
Lazy load json data from template engine (handlebars)

### ISSUE THREAD

**Issue by KieranRoberts44** [eisbehr-/jquery.lazy#90]
Hi Eisbehr,
I have been using your lazy load plugin and its great but I am having trouble with custom loaders.
I have posted a question on stackoverflow: http://stackoverflow.com/questions/43972781/lazy-load-json-data-from-template-engine-handlebars

If you would be possibly take the time to look at it, it would be greatly appreciated!
Cheers,
Kieran

**Comment by eisbehr-** [comment]
Hello @KieranRoberts44 

I don't know `handlebars` and how it works. So I can't help ypu with that. But what do you mean with problems with `custom loaders`? Do you mean Lazy's [custom loaders](https://github.com/eisbehr-/jquery.lazy#custom-content-loaders), or something from handlebars? Because I don't see any custom loader for Lazy in your code posted on SO.

Maybe if you tell me a bit more about what you want to do, I could give you some hints.

**Comment by KieranRoberts44** [comment]
Thanks for getting in touch!
Basically I am building my portfolio and I thought it would be a good idea to use a template engine (handlebars) and lazyload for efficiency and page load speed mainly.
My portfolio is currently here: https://kieranroberts44.github.io/
It's not much atm but I simply just want the images and project titles to lazy load.
I think the fact that I am using a template engine and json data is the tricky part.
Any advice you may have will be great :)

**Comment by eisbehr-** [comment]
But for me Lazy is working on your page?! It loads the images of your project.

**Comment by eisbehr-** [comment]
I took a script in your `script.js` file. The problem might be the order and timing of the script. Why not initialize Lazy just after your template is loaded? I even compressed your script a bit. ;)

That is the complete `script.js` file content:

```JS
$.getJSON("projects.json", function (data) {
    var list = $('#projects-list');
    var theTemplateScript = $("#projects-template").html();
    var theTemplate = Handlebars.compile(theTemplateScript);

    list.append(theTemplate(data));

    $('.lazy').lazy({
        effect: "fadeIn",
        effectTime: 5000,
        threshold: 0
    });
});
```

**Comment by KieranRoberts44** [comment]
Wow, thanks heaps! :)
I think it is the order and timing of the scripts, as I need to setTimeout on the lazyload function, so then it loads the content and then the lazyloading.
How would I get a slow transition on the project titles?? custom loader?

**Comment by KieranRoberts44** [comment]
Your compressed script works brilliantly! Thanks so much!

**Comment by eisbehr-** [comment]
A customer loder might be a bit overpowered here. I would remove the `effect` handling from lazy and use `callbacks` instead.

First, put a box around your template:

```HTML
<script id="projects-template" type="text/x-handlebars-template">​
  <img id="logo" class="lazy" src="{{logo.logo}}" />
  {{#each projects}}
  <div class="project">
    <h1 class="lazy" data-loader="customLoaderName">{{name}}</h1>
    <img class="lazy" data-src="{{image.small}}" />
  </div>
  {{/each}}
</script>
```

Per `css` set the project boxes to opacity zero and create a transition:

```CSS
.project {
  opacity: 0;
  transition: opacity 5s;
  -o-transition: opacity 5s;
  -moz-transition: opacity 5s;
  -webkit-transition: opacity 5s;
}
```

And then use callbacks to fade the boxes in, not the image alone:

```JS
$.getJSON("projects.json", function(data) {
    var theTemplateScript = $("#projects-template").html();
    var theTemplate = Handlebars.compile(theTemplateScript);

    $("#projects-list").append(theTemplate(data));

    $(".lazy").lazy({
        threshold: 0,
        afterLoad: function(element) {
            element.parent().css("opacity", 1);
        }
    });
});
```

It's not tested, but somhow like this it should work!

**Comment by eisbehr-** [comment]
I posted the answer on StackOverflow too, because the main problem was solved with my answer here. ;)

**Comment by KieranRoberts44** [comment]
You're a real legend! You have helped me immensely. Thank a bunch, I really do appreciate it :)
Also your code above works like treat.

**Comment by eisbehr-** [comment]
Glad it worked for you!
