### ISSUE TITLE
Delay loading for each of the images, is it possible?

### ISSUE THREAD

**Issue by azharp** [eisbehr-/jquery.lazy#91]
Firstly, great plugin! Thank you for taking your time to write this awesome plugin.

I was wondering if is possible to add some delay to load each of the images after the images entered the viewport/threshold?
What I'm trying to achieve is to make sure users read the image caption which in a separate layer and is visible initially before replacing it with actual images.
The existing delay options is for loading all the images at once and it's not ideal for my case.

Thank you.

**Comment by eisbehr-** [comment]
Hello @azharp 

You can do something by yourself. Take a look at this comment here: https://github.com/eisbehr-/jquery.lazy/issues/90#issuecomment-301711140
It will show you how to create an effect on your own. The only difference for you is, to add an delay in the callback, possible with `setTimeout`. Somhow like this:

```JS
$(".lazy").lazy({
    threshold: 0,
    afterLoad: function(element) {
        setTimeout(function() {
            element.parent().css("opacity", 1);
        }, 1000);
    }
});
```

**Comment by azharp** [comment]
Many thanks! Why I didn't thought of that before.
It's really close but the most ideal solution is to also add delay to image load so we can reduce the load time altogether.

I'm thinking to use a custom loader, do you think it would be a good approach?

**Comment by eisbehr-** [comment]
I don't get the idea behind your aproach?! Why would you want to delay the loading itself, and not the show only? I mean, every image what reaches the viewport will be loaded, with delay or not. So if more images reaches the viewport, the delay is the same and the images will be laoded together after the delay. You don't change anything, if the delay is the same for every image. You just delay the whole thing. ;)

And antoher advantage of just delaying the show of the image is, that you have more time to load the image. Whenever you want to show it, the image will be available instantly and don't delay it any further.

But maybe I don't get your intention. Please tell me then, why you think delay the loading would be better ...

**Comment by azharp** [comment]
I should explain it better LOL.

I'm using your plugins on an AJAX search feature so the users will be changing the keywords frequently. I'd like to avoid loading unnecessary images by only loading the images after the user finished typing for some time and/or change their cursor focus from the search form.

I will try to add some delay before initializing your plugin on the AJAX search, hopefully it work nicely.

Once again, thank you.

**Comment by eisbehr-** [comment]
When using something like an ajax serach, I would recommend to destroy the instance on search and recreate it afterwads. The reason is simply, that you you have many changing elements on this search. To just track the current available ones, you shoudl create a new instance. That can be done by `delay` config parameter too. I think this is what you want to do ...

**Comment by azharp** [comment]
Got it! Thank you for your input.

**Comment by eisbehr-** [comment]
You're welcome!
