### ISSUE TITLE
problem in bootstrap carousel lazy loading

### ISSUE THREAD

**Issue by casper66m** [eisbehr-/jquery.lazy#92]
Hi
Thanks for your work, I implement your code in my website, every thing works and is great, but bootstrap carousel have problem, For the first picture in carousel lazy loading works, but the rest of picture loaded with page loading and lazy loading do not effect on this pictures, How I can fix this problem?

**Comment by eisbehr-** [comment]
Hello @casper66m 

Thats because Lazy only load images initially or on `scroll` event. So you need to tell Lazy, when there is a content update, and load the new images. For this you can use the `.update()` public function of your lazy instance.

Or you exclude the carousel from lazy loading ... ;)

**Comment by casper66m** [comment]
Thanks for your response, All images in carousel except first image loaded with page loading, I want to prevent loading images before scroll to them, How implement update, I see your website and there is no example for update feature, I have several carousel in my website, how implement update
Thanks Again

**Comment by eisbehr-** [comment]
There is an example on the page and even here on github. Look for `public functions`. There you will find the `update` method.

But I can't tell you how to impelemt this in your website. I can't know every script out there, and I don't know bootstap carousel too. So you have to do things on your own ...
