### ISSUE TITLE
Can you share example for Audio and Video Tags?

### ISSUE THREAD

**Issue by kutec** [eisbehr-/jquery.lazy#93]
I am trying to implement plugin AV for `<audio>` and `<video>` tags but somehow it's not working. For images, it's working all good.

I tried out with below:
```
<video data-src="assets/file.mp4|video/mp4" data-poster="assets/poster.jpg"></video>
```
and
```
<video data-poster="assets/poster.jpg">
  <data-src src="assets/file.mp4" type="video/mp4"></data-src>
</video>
```
But none of above worked for me.

For images, I am adding:
```
$('img').Lazy({
        threshold: 0,
        combined: true,
        afterLoad: function(elem) {
            elem.css('opacity', 1);
        }
    });
```
_For video nothing?_

**Requesting you to share example snippets or JSFIDDLE.**

Thanks.

**Comment by eisbehr-** [comment]
Your examples look right. But did you have the [av plugin file included](https://github.com/eisbehr-/jquery.lazy/blob/master/plugins/README.md#about-loader-plugins) too?
