### ISSUE TITLE
Question about implementing this with macy.js masonry layout gallery

### ISSUE THREAD

**Issue by thedonquixotic** [eisbehr-/jquery.lazy#94]
First, I wanted to say, I love this plugin! It's great! The documentation and design are really well done. 

I'm fairly new to code though so I wanted to check if I was doing stuff the right way. 

I'm building a wordpress masonry layout gallery with lazy loading and light box, using Advanced Custom Fields plugin. 

The problem is, masonry layouts position images based upon image heights. So if I lazy load things, I think that's going to mess up the sizing of the masonry layout. I got lazy load working and [[it does this]](http://imgur.com/Zlz86SK). 

Basically the first set of images are all loading up but they're loading up on top of eachother because when they load they don't have a height set in the masonry layout. 

I noticed that when I reload the page, everything is actually fixed. Which made me think that maybe if I ran the macy.js init AFTER the jQuery.lazy init then it would be fixed, but alas things are not so simple. 

I'm a designer learning to program, but even then I feel like this seems like a pretty easy solution somewhere. I almost think I know what's going on, but I'm not sure and was hoping someone here might have some clues.

**Comment by eisbehr-** [comment]
I'll close this here, because it's dicsucced in comments on the project page.

**Comment by thedonquixotic** [comment]
Excellent thank you! I got it working yesterday :)
