### ISSUE TITLE
Not working with div's?

### ISSUE THREAD

**Issue by rica-carv** [eisbehr-/jquery.lazy#95]
I've got a page with this HTML structure:
```
<div class='lazy'>...content...</div>
<div class='lazy'>...content...</div>
<div class='lazy'>...content...</div>
<div class='lazy'>...content...</div>
```

and on the page end the js: 
```
https://cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.4/jquery.lazy.min.js
$('.lazy').Lazy();
```

But the page simply keeps loading all content, and keeps waiting for all div's content to load before display...

What am i doing wrong here?

**Comment by eisbehr-** [comment]
It seems that you are not very familiar with such techniques. You should at least know a bit of what you're doing. There are so many examples on the project page too, that you should see that it can't word this way... 

But nevermind, I answered some similar question some time ago on stackoverflow.com. Maybe read my post there, it should tell you what to do:

https://stackoverflow.com/questions/38760148/jquery-lazy-plugin-is-not-loading-my-li-contents

**Comment by rica-carv** [comment]
Sorry, my mistake, and not understanding that the script won't handle the whole HTML once outputed....

This way, i think i'll not use it, since i'll have to make a lot of AJAX and SQL calls...

Thanks anyway...

**Comment by eisbehr-** [comment]
It can't work without a backend. The html is rendered by the browser when it is responded. You have to do a workaround, in what way ever.
