### ISSUE TITLE
Does not work with document trigger used in ajax success

### ISSUE THREAD

**Issue by webangon** [eisbehr-/jquery.lazy#96]
Hi 

Great plugin . However it does not work with document trigger used in ajax callback. 
`$(document).trigger('load_filter_post');`
To use this trgger
```
 $(document).on('load_filter_post', load_filter_post);
    function load_filter_post() {
        $('.load-lazy').lazy(); // Doesn't work
       alert('Hi'); // Does work
    }
```

**Comment by eisbehr-** [comment]
You have to use `bind: "event"` config parameter, to start Lazy on such events.
