### ISSUE TITLE
Question about using jquery.lazy in sliders

### ISSUE THREAD

**Issue by TheRealJAG** [eisbehr-/jquery.lazy#97]
I have a few sliders on my page that I would like to lazy load (not load the numerous images that are queued in the background). I noticed however that when the image that is not exposed on initial load and when it comes in contact with the view it still shows the loading graphic. 

Is there a setting or a modification I can make to expose the image when it comes in contact with the viewpoint? 

Thanks and great plugin!

**Comment by eisbehr-** [comment]
Hello @TheRealJAG 

Lazy only loads images in viewport by scroll for default. So Lazy needs to know whenever new images of the slider hits the viewport. For this you need the [public function](https://github.com/eisbehr-/jquery.lazy#instances-and-public-functions) `.update()` of an Lazy instance. Whenever the slider changes the image, you need to call this function to tell Lazy that there are possible new images in the viewport.

That should do the trick. ;)
