### ISSUE TITLE
Lazy loading very slow for Edge browser or IE

### ISSUE THREAD

**Issue by webmasterpcx** [eisbehr-/jquery.lazy#99]
Hi there,

First, thanks for this amazing plugin. Very fast and lightweight.

Then, I have some issues when testing my website on Edge or IE11/10 (didn't try previous versions).
Browser is loading my page but when I scroll, my lazy load images are not appearing... alt tag is displayed instead. And when I wait for like 1min doing nothing, images are appearing !
Initial load :
![capture-edge-issue-initial-load](https://user-images.githubusercontent.com/30599842/28784765-ac16204a-7614-11e7-9412-b03105aac1f4.PNG)
After waiting for like 1min :
![capture-edge-issue-after-waiting](https://user-images.githubusercontent.com/30599842/28784766-ac1734f8-7614-11e7-82b1-e4b149306b22.PNG)

Do you know why this is happening ? No errors are showed on IE console. This is the first time I've experienced such a weird issue...

I hope you can help me.
Thank you.

Camille - Web developer

**Comment by eisbehr-** [comment]
Hello @webmasterpcx 

Well, that should not happen and I'm not completly sure why this happens. But I can't imagine why Lazy should delay the loading. Lazy uses regular image tags to load images in background. So the loading should be exactly the same like doing without. An IE/Edge should be no problem too!

To help you and to investigate the problem, would you please share a link, or even better, create a jsfiddle replicating the issue? Than I would take a look and try to help you.

**Comment by webmasterpcx** [comment]
Hi,

Thanks for your quick answer !
As my website is not accessible for visitors right now, I just created a Pen on Codepen where I was able to recreate my website with the issue.
Here's the link : (https://codepen.io/webmasterpcx/pen/xLVavJ)

If you open it on Edge browser or IE, you will see that images below the fold are not loaded. You have to wait a long time until they appear (like 1min at least I think).
Let me know if you're having troubles with my Pen.

I hope that you will be able to help me.
Thanks again,

Camille - Web developer

**Comment by eisbehr-** [comment]
The images in your example are all don't accessible for me. 😉

**Comment by webmasterpcx** [comment]
Oh yes... Is it better now ?
Sorry ! =)

**Comment by eisbehr-** [comment]
Okay, first big issue is that you have forgotten to set a correct `doctype` for your document! That makes you whole html document invalid at all. So please add a doctype at first and try if it will solve your problems. In my tests it fixed already other bugs with your page.

Just add `<!DOCTYPE html>` to the very first line of your html output.

**Comment by webmasterpcx** [comment]
Thanks, it's just that Codepen doesn't require a doctype on its pens. And I know that I have a few issues due to my unaccessible server or HTTPS.
Actually, on my original page, doctype is present and I have 0 errors in console. Still, image loading issue is happening on Edge.
I wouldn't want to waste your time, so if you think the problem is happening because of something by my side (server config, plugin incompatibility...), I will try to take care of it.
Thanks again =)

**Comment by eisbehr-** [comment]
I have copied the codepen to my local, because codepen is very, very slow. It was nearly not testable for me. I just copied everything, added css and js dependencies to the head and added the doctype. Then tested IE11, IE10 and Friefox. i have no problems at all! 

The images loaded directly and without any time to wait. I don't see any problem. And I would not know any reason what would cause this issue, beside a very slow connection/server. So I can't reproduce the problem.

Maybe helping you to debug the problem, you could add some options to Lazy. This would print debug messages to your console and the threashold is limited. Maybe this will give you a clue about the real logins times.

```JS
$(function($) {
    $("img.lazy").Lazy({
        threshold: 0,
        beforeLoad: function(e) {
            console.log("about to load " + e.attr("data-src"));
        },
        afterLoad: function(e) {
            console.log("loaded " + e.attr("src"));
        }
    });
});
```

**Comment by webmasterpcx** [comment]
Okay, very weird... I will try to debug with the code you gave me. If you have no problems on your side, I should be able to fix it.

Thank you very much for your help, I appreciate it ! =)
Have a nice day,

Camille - Web developer
